# Author: Dmitry Kuzmin (@xotonic) & Angel Leon (@gubatron)
# Original version: https://gist.github.com/gubatron/fd67cb0663b1ed53cb9eefb9561016b3
# README:
#
# This CMakeLists.txt file is not meant to produce any executables or libraries.
#
# It has been created for CLion or any other cmake compatible IDE users so that they can
# have their entire project built in such a way the IDE can index all symbols without errors.
#
# To build binaries, please use the original Makefile.
#
# Usage of this CMakeLists.txt from the command line
#
# NOTE: At this moment, cross-compilation paths are supported only (gcc i686-w64-mingw32 / Windows 10)
#

if($ENV{CLION_IDE})
    message(STATUS "CLION DETECTED")

    add_definitions(
            # GMP Bignum Library
            -DUSE_NUM_GMP=1
            -DUSE_FIELD_INV_NUM=1
            -DUSE_SCALAR_INV_NUM=1

            # secp256k1 flags
            # for 64bit
            -DUSE_BASIC_CONFIG=1
            -DUSE_FIELD_INV_BUILTIN=1
            -DUSE_SCALAR_INV_BUILTIN=1
            -DUSE_FIELD_10X26=1
            -DUSE_SCALAR_8X32
            -DHAVE___INT128=1

            -DJSON_TEST_SRC="${CMAKE_SOURCE_DIR}/src/univalue/test"
            -DENABLE_ZMQ=1

            -DHAVE_CONFIG_H=1
    )

    include_directories(
            depends/i686-w64-mingw32/include/openssl
            depends/i686-w64-mingw32/include
    )

    include_directories(
            src
            src/compat
            src/config
            src/consensus
            src/cpp-ethereum
            src/cpp-ethereum/bench
            src/cpp-ethereum/eth
            src/cpp-ethereum/ethkey
            src/cpp-ethereum/ethminer
            src/cpp-ethereum/ethvm
            src/cpp-ethereum/evmjit
            src/cpp-ethereum/evmjit/libevmjit
            src/cpp-ethereum/evmjit/libevmjit/preprocessor
            src/cpp-ethereum/evmjit/scripts
            src/cpp-ethereum/evmjit/tests
            src/cpp-ethereum/libdevcore
            src/cpp-ethereum/libdevcrypto
            src/cpp-ethereum/libethash
            src/cpp-ethereum/libethashseal
            src/cpp-ethereum/libethashseal/genesis
            src/cpp-ethereum/libethcore
            src/cpp-ethereum/libethereum
            src/cpp-ethereum/libevm
            src/cpp-ethereum/libevmcore
            src/cpp-ethereum/libp2p
            src/cpp-ethereum/libweb3jsonrpc
            src/cpp-ethereum/libwebthree
            src/cpp-ethereum/libwhisper
            src/cpp-ethereum/rlp
            src/cpp-ethereum/scripts
            src/cpp-ethereum/utils
            src/cpp-ethereum/utils/json_spirit
            src/cpp-ethereum/utils/libscrypt
            src/crypto
            src/crypto/lyra2
            src/cryptopp
            src/cryptopp/TestData
            src/cryptopp/TestScripts
            src/cryptopp/TestVectors
            src/json
            src/leveldb
            src/leveldb/db
            src/leveldb/helpers
            src/leveldb/helpers/memenv
            src/leveldb/include
            src/leveldb/include/leveldb
            src/leveldb/issues
            src/leveldb/port
            src/leveldb/port/win
            src/leveldb/table
            src/leveldb/util
            src/lux
            src/luxgate
            src/luxgate/devtools
            src/luxgate/sql
            src/luxgate/test
            src/obj
            src/obj/crypto
            src/obj-test
            src/policy
            src/primitives
            src/qt
            src/qt/forms
            src/script
            src/secp256k1
            src/secp256k1/autom4te.cache
            src/secp256k1/build-aux
            src/secp256k1/build-aux/m4
            src/secp256k1/contrib
            src/secp256k1/include
            src/secp256k1/obj
            src/secp256k1/sage
            src/secp256k1/src
            src/secp256k1/src/asm
            src/secp256k1/src/modules
            src/secp256k1/src/modules/ecdh
            src/secp256k1/src/modules/recovery
            src/secp256k1/src/modules/schnorr
            src/support
            src/support/allocators
            src/test
            src/test/data
            src/univalue
            src/zmq
    )

    get_property(dirs DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR} PROPERTY INCLUDE_DIRECTORIES)
    foreach(dir ${dirs})
        message(STATUS "dir='${dir}'")
    endforeach()

    set(SOURCE_FILES
            depends/i686-w64-mingw32/include/boost/container/detail/alloc_lib.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/alpha.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/arm.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/blackfin.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/convex.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/ia64.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/m68k.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/mips.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/parisc.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/ppc.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/pyramid.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/rs6k.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/sparc.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/superh.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/sys370.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/sys390.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/x86/32.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/x86/64.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/x86.h
            depends/i686-w64-mingw32/include/boost/predef/architecture/z.h
            depends/i686-w64-mingw32/include/boost/predef/architecture.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/borland.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/clang.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/comeau.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/compaq.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/diab.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/digitalmars.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/dignus.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/edg.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/ekopath.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/gcc.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/gcc_xml.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/greenhills.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/hp_acc.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/iar.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/ibm.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/intel.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/kai.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/llvm.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/metaware.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/metrowerks.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/microtec.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/mpw.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/palm.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/pgi.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/sgi_mipspro.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/sunpro.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/tendra.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/visualc.h
            depends/i686-w64-mingw32/include/boost/predef/compiler/watcom.h
            depends/i686-w64-mingw32/include/boost/predef/compiler.h
            depends/i686-w64-mingw32/include/boost/predef/detail/comp_detected.h
            depends/i686-w64-mingw32/include/boost/predef/detail/endian_compat.h
            depends/i686-w64-mingw32/include/boost/predef/detail/os_detected.h
            depends/i686-w64-mingw32/include/boost/predef/detail/platform_detected.h
            depends/i686-w64-mingw32/include/boost/predef/detail/test.h
            depends/i686-w64-mingw32/include/boost/predef/detail/test_def.h
            depends/i686-w64-mingw32/include/boost/predef/detail/_cassert.h
            depends/i686-w64-mingw32/include/boost/predef/detail/_exception.h
            depends/i686-w64-mingw32/include/boost/predef/hardware/simd/arm/versions.h
            depends/i686-w64-mingw32/include/boost/predef/hardware/simd/arm.h
            depends/i686-w64-mingw32/include/boost/predef/hardware/simd/ppc/versions.h
            depends/i686-w64-mingw32/include/boost/predef/hardware/simd/ppc.h
            depends/i686-w64-mingw32/include/boost/predef/hardware/simd/x86/versions.h
            depends/i686-w64-mingw32/include/boost/predef/hardware/simd/x86.h
            depends/i686-w64-mingw32/include/boost/predef/hardware/simd/x86_amd/versions.h
            depends/i686-w64-mingw32/include/boost/predef/hardware/simd/x86_amd.h
            depends/i686-w64-mingw32/include/boost/predef/hardware/simd.h
            depends/i686-w64-mingw32/include/boost/predef/hardware.h
            depends/i686-w64-mingw32/include/boost/predef/language/objc.h
            depends/i686-w64-mingw32/include/boost/predef/language/stdc.h
            depends/i686-w64-mingw32/include/boost/predef/language/stdcpp.h
            depends/i686-w64-mingw32/include/boost/predef/language.h
            depends/i686-w64-mingw32/include/boost/predef/library/c/gnu.h
            depends/i686-w64-mingw32/include/boost/predef/library/c/uc.h
            depends/i686-w64-mingw32/include/boost/predef/library/c/vms.h
            depends/i686-w64-mingw32/include/boost/predef/library/c/zos.h
            depends/i686-w64-mingw32/include/boost/predef/library/c/_prefix.h
            depends/i686-w64-mingw32/include/boost/predef/library/c.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/cxx.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/dinkumware.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/libcomo.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/modena.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/msl.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/roguewave.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/sgi.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/stdcpp3.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/stlport.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/vacpp.h
            depends/i686-w64-mingw32/include/boost/predef/library/std/_prefix.h
            depends/i686-w64-mingw32/include/boost/predef/library/std.h
            depends/i686-w64-mingw32/include/boost/predef/library.h
            depends/i686-w64-mingw32/include/boost/predef/make.h
            depends/i686-w64-mingw32/include/boost/predef/os/aix.h
            depends/i686-w64-mingw32/include/boost/predef/os/amigaos.h
            depends/i686-w64-mingw32/include/boost/predef/os/android.h
            depends/i686-w64-mingw32/include/boost/predef/os/beos.h
            depends/i686-w64-mingw32/include/boost/predef/os/bsd/bsdi.h
            depends/i686-w64-mingw32/include/boost/predef/os/bsd/dragonfly.h
            depends/i686-w64-mingw32/include/boost/predef/os/bsd/free.h
            depends/i686-w64-mingw32/include/boost/predef/os/bsd/net.h
            depends/i686-w64-mingw32/include/boost/predef/os/bsd/open.h
            depends/i686-w64-mingw32/include/boost/predef/os/bsd.h
            depends/i686-w64-mingw32/include/boost/predef/os/cygwin.h
            depends/i686-w64-mingw32/include/boost/predef/os/haiku.h
            depends/i686-w64-mingw32/include/boost/predef/os/hpux.h
            depends/i686-w64-mingw32/include/boost/predef/os/ios.h
            depends/i686-w64-mingw32/include/boost/predef/os/irix.h
            depends/i686-w64-mingw32/include/boost/predef/os/linux.h
            depends/i686-w64-mingw32/include/boost/predef/os/macos.h
            depends/i686-w64-mingw32/include/boost/predef/os/os400.h
            depends/i686-w64-mingw32/include/boost/predef/os/qnxnto.h
            depends/i686-w64-mingw32/include/boost/predef/os/solaris.h
            depends/i686-w64-mingw32/include/boost/predef/os/unix.h
            depends/i686-w64-mingw32/include/boost/predef/os/vms.h
            depends/i686-w64-mingw32/include/boost/predef/os/windows.h
            depends/i686-w64-mingw32/include/boost/predef/os.h
            depends/i686-w64-mingw32/include/boost/predef/other/endian.h
            depends/i686-w64-mingw32/include/boost/predef/other.h
            depends/i686-w64-mingw32/include/boost/predef/platform/mingw.h
            depends/i686-w64-mingw32/include/boost/predef/platform/windows_desktop.h
            depends/i686-w64-mingw32/include/boost/predef/platform/windows_phone.h
            depends/i686-w64-mingw32/include/boost/predef/platform/windows_runtime.h
            depends/i686-w64-mingw32/include/boost/predef/platform/windows_store.h
            depends/i686-w64-mingw32/include/boost/predef/platform.h
            depends/i686-w64-mingw32/include/boost/predef/version.h
            depends/i686-w64-mingw32/include/boost/predef/version_number.h
            depends/i686-w64-mingw32/include/boost/predef.h
            depends/i686-w64-mingw32/include/boost/python/detail/python22_fixed.h
            depends/i686-w64-mingw32/include/boost/regex.h
            depends/i686-w64-mingw32/include/boost/tr1/tr1/bcc32/array.h
            depends/i686-w64-mingw32/include/boost/tr1/tr1/bcc32/random.h
            depends/i686-w64-mingw32/include/boost/tr1/tr1/bcc32/regex.h
            depends/i686-w64-mingw32/include/boost/tr1/tr1/bcc32/tuple.h
            depends/i686-w64-mingw32/include/boost/tr1/tr1/bcc32/type_tra.h
            depends/i686-w64-mingw32/include/boost/tr1/tr1/bcc32/unordere.h
            depends/i686-w64-mingw32/include/db.h
            depends/i686-w64-mingw32/include/db_cxx.h
            depends/i686-w64-mingw32/include/evdns.h
            depends/i686-w64-mingw32/include/event.h
            depends/i686-w64-mingw32/include/event2/buffer.h
            depends/i686-w64-mingw32/include/event2/bufferevent.h
            depends/i686-w64-mingw32/include/event2/bufferevent_compat.h
            depends/i686-w64-mingw32/include/event2/bufferevent_ssl.h
            depends/i686-w64-mingw32/include/event2/bufferevent_struct.h
            depends/i686-w64-mingw32/include/event2/buffer_compat.h
            depends/i686-w64-mingw32/include/event2/dns.h
            depends/i686-w64-mingw32/include/event2/dns_compat.h
            depends/i686-w64-mingw32/include/event2/dns_struct.h
            depends/i686-w64-mingw32/include/event2/event-config.h
            depends/i686-w64-mingw32/include/event2/event.h
            depends/i686-w64-mingw32/include/event2/event_compat.h
            depends/i686-w64-mingw32/include/event2/event_struct.h
            depends/i686-w64-mingw32/include/event2/http.h
            depends/i686-w64-mingw32/include/event2/http_compat.h
            depends/i686-w64-mingw32/include/event2/http_struct.h
            depends/i686-w64-mingw32/include/event2/keyvalq_struct.h
            depends/i686-w64-mingw32/include/event2/listener.h
            depends/i686-w64-mingw32/include/event2/rpc.h
            depends/i686-w64-mingw32/include/event2/rpc_compat.h
            depends/i686-w64-mingw32/include/event2/rpc_struct.h
            depends/i686-w64-mingw32/include/event2/tag.h
            depends/i686-w64-mingw32/include/event2/tag_compat.h
            depends/i686-w64-mingw32/include/event2/thread.h
            depends/i686-w64-mingw32/include/event2/util.h
            depends/i686-w64-mingw32/include/event2/visibility.h
            depends/i686-w64-mingw32/include/evhttp.h
            depends/i686-w64-mingw32/include/evrpc.h
            depends/i686-w64-mingw32/include/evutil.h
            depends/i686-w64-mingw32/include/google/protobuf/compiler/code_generator.h
            depends/i686-w64-mingw32/include/google/protobuf/compiler/command_line_interface.h
            depends/i686-w64-mingw32/include/google/protobuf/compiler/cpp/cpp_generator.h
            depends/i686-w64-mingw32/include/google/protobuf/compiler/importer.h
            depends/i686-w64-mingw32/include/google/protobuf/compiler/java/java_generator.h
            depends/i686-w64-mingw32/include/google/protobuf/compiler/parser.h
            depends/i686-w64-mingw32/include/google/protobuf/compiler/plugin.h
            depends/i686-w64-mingw32/include/google/protobuf/compiler/plugin.pb.h
            depends/i686-w64-mingw32/include/google/protobuf/compiler/python/python_generator.h
            depends/i686-w64-mingw32/include/google/protobuf/descriptor.h
            depends/i686-w64-mingw32/include/google/protobuf/descriptor.pb.h
            depends/i686-w64-mingw32/include/google/protobuf/descriptor_database.h
            depends/i686-w64-mingw32/include/google/protobuf/dynamic_message.h
            depends/i686-w64-mingw32/include/google/protobuf/extension_set.h
            depends/i686-w64-mingw32/include/google/protobuf/generated_enum_reflection.h
            depends/i686-w64-mingw32/include/google/protobuf/generated_message_reflection.h
            depends/i686-w64-mingw32/include/google/protobuf/generated_message_util.h
            depends/i686-w64-mingw32/include/google/protobuf/io/coded_stream.h
            depends/i686-w64-mingw32/include/google/protobuf/io/printer.h
            depends/i686-w64-mingw32/include/google/protobuf/io/strtod.h
            depends/i686-w64-mingw32/include/google/protobuf/io/tokenizer.h
            depends/i686-w64-mingw32/include/google/protobuf/io/zero_copy_stream.h
            depends/i686-w64-mingw32/include/google/protobuf/io/zero_copy_stream_impl.h
            depends/i686-w64-mingw32/include/google/protobuf/io/zero_copy_stream_impl_lite.h
            depends/i686-w64-mingw32/include/google/protobuf/message.h
            depends/i686-w64-mingw32/include/google/protobuf/message_lite.h
            depends/i686-w64-mingw32/include/google/protobuf/reflection_ops.h
            depends/i686-w64-mingw32/include/google/protobuf/repeated_field.h
            depends/i686-w64-mingw32/include/google/protobuf/service.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_arm64_gcc.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_arm_gcc.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_arm_qnx.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_atomicword_compat.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_generic_gcc.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_macosx.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_mips_gcc.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_pnacl.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_solaris.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_tsan.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_x86_gcc.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/atomicops_internals_x86_msvc.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/common.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/once.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/platform_macros.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/stl_util.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/template_util.h
            depends/i686-w64-mingw32/include/google/protobuf/stubs/type_traits.h
            depends/i686-w64-mingw32/include/google/protobuf/text_format.h
            depends/i686-w64-mingw32/include/google/protobuf/unknown_field_set.h
            depends/i686-w64-mingw32/include/google/protobuf/wire_format.h
            depends/i686-w64-mingw32/include/google/protobuf/wire_format_lite.h
            depends/i686-w64-mingw32/include/google/protobuf/wire_format_lite_inl.h
            depends/i686-w64-mingw32/include/leveldb/c.h
            depends/i686-w64-mingw32/include/leveldb/cache.h
            depends/i686-w64-mingw32/include/leveldb/comparator.h
            depends/i686-w64-mingw32/include/leveldb/db.h
            depends/i686-w64-mingw32/include/leveldb/dumpfile.h
            depends/i686-w64-mingw32/include/leveldb/env.h
            depends/i686-w64-mingw32/include/leveldb/filter_policy.h
            depends/i686-w64-mingw32/include/leveldb/helpers/memenv.h
            depends/i686-w64-mingw32/include/leveldb/iterator.h
            depends/i686-w64-mingw32/include/leveldb/options.h
            depends/i686-w64-mingw32/include/leveldb/slice.h
            depends/i686-w64-mingw32/include/leveldb/status.h
            depends/i686-w64-mingw32/include/leveldb/table.h
            depends/i686-w64-mingw32/include/leveldb/table_builder.h
            depends/i686-w64-mingw32/include/leveldb/write_batch.h
            depends/i686-w64-mingw32/include/miniupnpc/codelength.h
            depends/i686-w64-mingw32/include/miniupnpc/connecthostport.h
            depends/i686-w64-mingw32/include/miniupnpc/igd_desc_parse.h
            depends/i686-w64-mingw32/include/miniupnpc/minisoap.h
            depends/i686-w64-mingw32/include/miniupnpc/minissdpc.h
            depends/i686-w64-mingw32/include/miniupnpc/miniupnpc.h
            depends/i686-w64-mingw32/include/miniupnpc/miniupnpcstrings.h
            depends/i686-w64-mingw32/include/miniupnpc/miniupnpctypes.h
            depends/i686-w64-mingw32/include/miniupnpc/miniupnpc_declspec.h
            depends/i686-w64-mingw32/include/miniupnpc/miniwget.h
            depends/i686-w64-mingw32/include/miniupnpc/minixml.h
            depends/i686-w64-mingw32/include/miniupnpc/portlistingparse.h
            depends/i686-w64-mingw32/include/miniupnpc/receivedata.h
            depends/i686-w64-mingw32/include/miniupnpc/upnpcommands.h
            depends/i686-w64-mingw32/include/miniupnpc/upnpdev.h
            depends/i686-w64-mingw32/include/miniupnpc/upnperrors.h
            depends/i686-w64-mingw32/include/miniupnpc/upnpreplyparse.h
            depends/i686-w64-mingw32/include/openssl/aes.h
            depends/i686-w64-mingw32/include/openssl/asn1.h
            depends/i686-w64-mingw32/include/openssl/asn1t.h
            depends/i686-w64-mingw32/include/openssl/asn1_mac.h
            depends/i686-w64-mingw32/include/openssl/bio.h
            depends/i686-w64-mingw32/include/openssl/blowfish.h
            depends/i686-w64-mingw32/include/openssl/bn.h
            depends/i686-w64-mingw32/include/openssl/buffer.h
            depends/i686-w64-mingw32/include/openssl/cmac.h
            depends/i686-w64-mingw32/include/openssl/cms.h
            depends/i686-w64-mingw32/include/openssl/conf.h
            depends/i686-w64-mingw32/include/openssl/conf_api.h
            depends/i686-w64-mingw32/include/openssl/crypto.h
            depends/i686-w64-mingw32/include/openssl/des.h
            depends/i686-w64-mingw32/include/openssl/des_old.h
            depends/i686-w64-mingw32/include/openssl/dh.h
            depends/i686-w64-mingw32/include/openssl/dsa.h
            depends/i686-w64-mingw32/include/openssl/dso.h
            depends/i686-w64-mingw32/include/openssl/dtls1.h
            depends/i686-w64-mingw32/include/openssl/ebcdic.h
            depends/i686-w64-mingw32/include/openssl/ec.h
            depends/i686-w64-mingw32/include/openssl/ecdh.h
            depends/i686-w64-mingw32/include/openssl/ecdsa.h
            depends/i686-w64-mingw32/include/openssl/engine.h
            depends/i686-w64-mingw32/include/openssl/err.h
            depends/i686-w64-mingw32/include/openssl/evp.h
            depends/i686-w64-mingw32/include/openssl/e_os2.h
            depends/i686-w64-mingw32/include/openssl/hmac.h
            depends/i686-w64-mingw32/include/openssl/krb5_asn.h
            depends/i686-w64-mingw32/include/openssl/kssl.h
            depends/i686-w64-mingw32/include/openssl/lhash.h
            depends/i686-w64-mingw32/include/openssl/md4.h
            depends/i686-w64-mingw32/include/openssl/md5.h
            depends/i686-w64-mingw32/include/openssl/modes.h
            depends/i686-w64-mingw32/include/openssl/objects.h
            depends/i686-w64-mingw32/include/openssl/obj_mac.h
            depends/i686-w64-mingw32/include/openssl/ocsp.h
            depends/i686-w64-mingw32/include/openssl/opensslconf.h
            depends/i686-w64-mingw32/include/openssl/opensslv.h
            depends/i686-w64-mingw32/include/openssl/ossl_typ.h
            depends/i686-w64-mingw32/include/openssl/pem.h
            depends/i686-w64-mingw32/include/openssl/pem2.h
            depends/i686-w64-mingw32/include/openssl/pkcs12.h
            depends/i686-w64-mingw32/include/openssl/pkcs7.h
            depends/i686-w64-mingw32/include/openssl/pqueue.h
            depends/i686-w64-mingw32/include/openssl/rand.h
            depends/i686-w64-mingw32/include/openssl/rc2.h
            depends/i686-w64-mingw32/include/openssl/ripemd.h
            depends/i686-w64-mingw32/include/openssl/rsa.h
            depends/i686-w64-mingw32/include/openssl/safestack.h
            depends/i686-w64-mingw32/include/openssl/sha.h
            depends/i686-w64-mingw32/include/openssl/srp.h
            depends/i686-w64-mingw32/include/openssl/srtp.h
            depends/i686-w64-mingw32/include/openssl/ssl.h
            depends/i686-w64-mingw32/include/openssl/ssl2.h
            depends/i686-w64-mingw32/include/openssl/ssl23.h
            depends/i686-w64-mingw32/include/openssl/ssl3.h
            depends/i686-w64-mingw32/include/openssl/stack.h
            depends/i686-w64-mingw32/include/openssl/symhacks.h
            depends/i686-w64-mingw32/include/openssl/tls1.h
            depends/i686-w64-mingw32/include/openssl/ts.h
            depends/i686-w64-mingw32/include/openssl/txt_db.h
            depends/i686-w64-mingw32/include/openssl/ui.h
            depends/i686-w64-mingw32/include/openssl/ui_compat.h
            depends/i686-w64-mingw32/include/openssl/x509.h
            depends/i686-w64-mingw32/include/openssl/x509v3.h
            depends/i686-w64-mingw32/include/openssl/x509_vfy.h
            depends/i686-w64-mingw32/include/qrencode.h
            depends/i686-w64-mingw32/include/zconf.h
            depends/i686-w64-mingw32/include/zlib.h
            depends/i686-w64-mingw32/include/zmq.h
            depends/i686-w64-mingw32/include/zmq_utils.h
            depends/patches/qt/uiviewsettingsinterop.h
            src/activemasternode.cpp
            src/activemasternode.h
            src/addressindex.h
            src/addrman.cpp
            src/addrman.h
            src/alert.cpp
            src/alert.h
            src/allocators.cpp
            src/allocators.h
            src/amount.cpp
            src/amount.h
            src/arith_uint256.cpp
            src/arith_uint256.h
            src/base58.cpp
            src/base58.h
            src/bech32.cpp
            src/bech32.h
            src/bip38.cpp
            src/bip38.h
            src/bip39.cpp
            src/bip39.h
            src/bip39_english.h
            src/bloom.cpp
            src/bloom.h
            src/chain.cpp
            src/chain.h
            src/chainparams.cpp
            src/chainparams.h
            src/chainparamsbase.cpp
            src/chainparamsbase.h
            src/chainparamsseeds.h
            src/checkpoints.cpp
            src/checkpoints.h
            src/checkqueue.h
            src/clientversion.cpp
            src/clientversion.h
            src/coincontrol.h
            src/coins.cpp
            src/coins.h
            src/compat/byteswap.h
            src/compat/endian.h
            src/compat/glibcxx_compat.cpp
            src/compat/glibcxx_sanity.cpp
            src/compat/glibc_compat.cpp
            src/compat/glibc_sanity.cpp
            src/compat/sanity.h
            src/compat/strnlen.cpp
            src/compat.h
            src/compressor.cpp
            src/compressor.h
            src/config/lux-config.h
            src/consensus/consensus.h
            src/consensus/merkle.cpp
            src/consensus/merkle.h
            src/consensus/params.h
            src/consensus/validation.cpp
            src/consensus/validation.h
            src/core_io.h
            src/core_memusage.h
            src/core_read.cpp
            src/core_write.cpp
            src/cpp-ethereum/bench/main.cpp
            src/cpp-ethereum/eth/AccountManager.cpp
            src/cpp-ethereum/eth/AccountManager.h
            src/cpp-ethereum/eth/Farm.h
            src/cpp-ethereum/eth/main.cpp
            src/cpp-ethereum/ethkey/KeyAux.h
            src/cpp-ethereum/ethkey/main.cpp
            src/cpp-ethereum/ethminer/FarmClient.h
            src/cpp-ethereum/ethminer/main.cpp
            src/cpp-ethereum/ethminer/MinerAux.h
            src/cpp-ethereum/ethvm/main.cpp
            src/cpp-ethereum/evmjit/examples/capi.c
            src/cpp-ethereum/evmjit/examples/examplevm.c
            src/cpp-ethereum/evmjit/libevmjit/Arith256.cpp
            src/cpp-ethereum/evmjit/libevmjit/Arith256.h
            src/cpp-ethereum/evmjit/libevmjit/Array.cpp
            src/cpp-ethereum/evmjit/libevmjit/Array.h
            src/cpp-ethereum/evmjit/libevmjit/BasicBlock.cpp
            src/cpp-ethereum/evmjit/libevmjit/BasicBlock.h
            src/cpp-ethereum/evmjit/libevmjit/Cache.cpp
            src/cpp-ethereum/evmjit/libevmjit/Cache.h
            src/cpp-ethereum/evmjit/libevmjit/Common.h
            src/cpp-ethereum/evmjit/libevmjit/Compiler.cpp
            src/cpp-ethereum/evmjit/libevmjit/Compiler.h
            src/cpp-ethereum/evmjit/libevmjit/CompilerHelper.cpp
            src/cpp-ethereum/evmjit/libevmjit/CompilerHelper.h
            src/cpp-ethereum/evmjit/libevmjit/Endianness.cpp
            src/cpp-ethereum/evmjit/libevmjit/Endianness.h
            src/cpp-ethereum/evmjit/libevmjit/ExecStats.cpp
            src/cpp-ethereum/evmjit/libevmjit/ExecStats.h
            src/cpp-ethereum/evmjit/libevmjit/Ext.cpp
            src/cpp-ethereum/evmjit/libevmjit/Ext.h
            src/cpp-ethereum/evmjit/libevmjit/GasMeter.cpp
            src/cpp-ethereum/evmjit/libevmjit/GasMeter.h
            src/cpp-ethereum/evmjit/libevmjit/Instruction.cpp
            src/cpp-ethereum/evmjit/libevmjit/Instruction.h
            src/cpp-ethereum/evmjit/libevmjit/JIT.cpp
            src/cpp-ethereum/evmjit/libevmjit/JIT.h
            src/cpp-ethereum/evmjit/libevmjit/Memory.cpp
            src/cpp-ethereum/evmjit/libevmjit/Memory.h
            src/cpp-ethereum/evmjit/libevmjit/Optimizer.cpp
            src/cpp-ethereum/evmjit/libevmjit/Optimizer.h
            src/cpp-ethereum/evmjit/libevmjit/preprocessor/llvm_includes_end.h
            src/cpp-ethereum/evmjit/libevmjit/preprocessor/llvm_includes_start.h
            src/cpp-ethereum/evmjit/libevmjit/RuntimeManager.cpp
            src/cpp-ethereum/evmjit/libevmjit/RuntimeManager.h
            src/cpp-ethereum/evmjit/libevmjit/Type.cpp
            src/cpp-ethereum/evmjit/libevmjit/Type.h
            src/cpp-ethereum/evmjit/libevmjit/Utils.cpp
            src/cpp-ethereum/evmjit/libevmjit/Utils.h
            src/cpp-ethereum/evmjit/tests/test-evm.cpp
            src/cpp-ethereum/evmjit/tests/test-evmjit-standalone.c
            src/cpp-ethereum/libdevcore/Assertions.h
            src/cpp-ethereum/libdevcore/Base64.cpp
            src/cpp-ethereum/libdevcore/Base64.h
            src/cpp-ethereum/libdevcore/Common.cpp
            src/cpp-ethereum/libdevcore/Common.h
            src/cpp-ethereum/libdevcore/CommonData.cpp
            src/cpp-ethereum/libdevcore/CommonData.h
            src/cpp-ethereum/libdevcore/CommonIO.cpp
            src/cpp-ethereum/libdevcore/CommonIO.h
            src/cpp-ethereum/libdevcore/CommonJS.cpp
            src/cpp-ethereum/libdevcore/CommonJS.h
            src/cpp-ethereum/libdevcore/concurrent_queue.h
            src/cpp-ethereum/libdevcore/db.h
            src/cpp-ethereum/libdevcore/debugbreak.h
            src/cpp-ethereum/libdevcore/Exceptions.h
            src/cpp-ethereum/libdevcore/FileSystem.cpp
            src/cpp-ethereum/libdevcore/FileSystem.h
            src/cpp-ethereum/libdevcore/FixedHash.cpp
            src/cpp-ethereum/libdevcore/FixedHash.h
            src/cpp-ethereum/libdevcore/Guards.cpp
            src/cpp-ethereum/libdevcore/Guards.h
            src/cpp-ethereum/libdevcore/Hash.cpp
            src/cpp-ethereum/libdevcore/Hash.h
            src/cpp-ethereum/libdevcore/Log.cpp
            src/cpp-ethereum/libdevcore/Log.h
            src/cpp-ethereum/libdevcore/MemoryDB.cpp
            src/cpp-ethereum/libdevcore/MemoryDB.h
            src/cpp-ethereum/libdevcore/OverlayDB.cpp
            src/cpp-ethereum/libdevcore/OverlayDB.h
            src/cpp-ethereum/libdevcore/picosha2.h
            src/cpp-ethereum/libdevcore/RangeMask.h
            src/cpp-ethereum/libdevcore/RLP.cpp
            src/cpp-ethereum/libdevcore/RLP.h
            src/cpp-ethereum/libdevcore/SHA3.cpp
            src/cpp-ethereum/libdevcore/SHA3.h
            src/cpp-ethereum/libdevcore/Terminal.h
            src/cpp-ethereum/libdevcore/TransientDirectory.cpp
            src/cpp-ethereum/libdevcore/TransientDirectory.h
            src/cpp-ethereum/libdevcore/TrieCommon.cpp
            src/cpp-ethereum/libdevcore/TrieCommon.h
            src/cpp-ethereum/libdevcore/TrieDB.cpp
            src/cpp-ethereum/libdevcore/TrieDB.h
            src/cpp-ethereum/libdevcore/TrieHash.cpp
            src/cpp-ethereum/libdevcore/TrieHash.h
            src/cpp-ethereum/libdevcore/UndefMacros.h
            src/cpp-ethereum/libdevcore/vector_ref.h
            src/cpp-ethereum/libdevcore/Worker.cpp
            src/cpp-ethereum/libdevcore/Worker.h
            src/cpp-ethereum/libdevcrypto/AES.cpp
            src/cpp-ethereum/libdevcrypto/AES.h
            src/cpp-ethereum/libdevcrypto/Common.cpp
            src/cpp-ethereum/libdevcrypto/Common.h
            src/cpp-ethereum/libdevcrypto/CryptoPP.cpp
            src/cpp-ethereum/libdevcrypto/CryptoPP.h
            src/cpp-ethereum/libdevcrypto/ECDHE.cpp
            src/cpp-ethereum/libdevcrypto/ECDHE.h
            src/cpp-ethereum/libdevcrypto/Exceptions.h
            src/cpp-ethereum/libdevcrypto/SecretStore.cpp
            src/cpp-ethereum/libdevcrypto/SecretStore.h
            src/cpp-ethereum/libethash/compiler.h
            src/cpp-ethereum/libethash/data_sizes.h
            src/cpp-ethereum/libethash/endian.h
            src/cpp-ethereum/libethash/ethash.h
            src/cpp-ethereum/libethash/fnv.h
            src/cpp-ethereum/libethash/internal.c
            src/cpp-ethereum/libethash/internal.h
            src/cpp-ethereum/libethash/io.c
            src/cpp-ethereum/libethash/io.h
            src/cpp-ethereum/libethash/io_posix.c
            src/cpp-ethereum/libethash/io_win32.c
            src/cpp-ethereum/libethash/mmap.h
            src/cpp-ethereum/libethash/mmap_win32.c
            src/cpp-ethereum/libethash/sha3.c
            src/cpp-ethereum/libethash/sha3.h
            src/cpp-ethereum/libethash/util.c
            src/cpp-ethereum/libethash/util.h
            src/cpp-ethereum/libethash/util_win32.c
            src/cpp-ethereum/libethashseal/Ethash.cpp
            src/cpp-ethereum/libethashseal/Ethash.h
            src/cpp-ethereum/libethashseal/EthashAux.cpp
            src/cpp-ethereum/libethashseal/EthashAux.h
            src/cpp-ethereum/libethashseal/EthashClient.cpp
            src/cpp-ethereum/libethashseal/EthashClient.h
            src/cpp-ethereum/libethashseal/EthashCPUMiner.cpp
            src/cpp-ethereum/libethashseal/EthashCPUMiner.h
            src/cpp-ethereum/libethashseal/EthashProofOfWork.cpp
            src/cpp-ethereum/libethashseal/EthashProofOfWork.h
            src/cpp-ethereum/libethashseal/genesis/eip150Test.cpp
            src/cpp-ethereum/libethashseal/genesis/eip158Test.cpp
            src/cpp-ethereum/libethashseal/genesis/frontierTest.cpp
            src/cpp-ethereum/libethashseal/genesis/homesteadTest.cpp
            src/cpp-ethereum/libethashseal/genesis/luxMainNetwork.cpp
            src/cpp-ethereum/libethashseal/genesis/luxTestNetwork.cpp
            src/cpp-ethereum/libethashseal/genesis/mainNetwork.cpp
            src/cpp-ethereum/libethashseal/genesis/mainNetworkTest.cpp
            src/cpp-ethereum/libethashseal/genesis/metropolisTest.cpp
            src/cpp-ethereum/libethashseal/genesis/ropsten.cpp
            src/cpp-ethereum/libethashseal/genesis/transitionnetTest.cpp
            src/cpp-ethereum/libethashseal/GenesisInfo.cpp
            src/cpp-ethereum/libethashseal/GenesisInfo.h
            src/cpp-ethereum/libethcore/ABI.cpp
            src/cpp-ethereum/libethcore/ABI.h
            src/cpp-ethereum/libethcore/BasicAuthority.cpp
            src/cpp-ethereum/libethcore/BasicAuthority.h
            src/cpp-ethereum/libethcore/BlockHeader.cpp
            src/cpp-ethereum/libethcore/BlockHeader.h
            src/cpp-ethereum/libethcore/ChainOperationParams.cpp
            src/cpp-ethereum/libethcore/ChainOperationParams.h
            src/cpp-ethereum/libethcore/Common.cpp
            src/cpp-ethereum/libethcore/Common.h
            src/cpp-ethereum/libethcore/CommonJS.cpp
            src/cpp-ethereum/libethcore/CommonJS.h
            src/cpp-ethereum/libethcore/Exceptions.h
            src/cpp-ethereum/libethcore/ICAP.cpp
            src/cpp-ethereum/libethcore/ICAP.h
            src/cpp-ethereum/libethcore/KeyManager.cpp
            src/cpp-ethereum/libethcore/KeyManager.h
            src/cpp-ethereum/libethcore/Precompiled.cpp
            src/cpp-ethereum/libethcore/Precompiled.h
            src/cpp-ethereum/libethcore/SealEngine.cpp
            src/cpp-ethereum/libethcore/SealEngine.h
            src/cpp-ethereum/libethcore/Transaction.cpp
            src/cpp-ethereum/libethcore/Transaction.h
            src/cpp-ethereum/libethereum/Account.cpp
            src/cpp-ethereum/libethereum/Account.h
            src/cpp-ethereum/libethereum/BasicGasPricer.cpp
            src/cpp-ethereum/libethereum/BasicGasPricer.h
            src/cpp-ethereum/libethereum/Block.cpp
            src/cpp-ethereum/libethereum/Block.h
            src/cpp-ethereum/libethereum/BlockChain.cpp
            src/cpp-ethereum/libethereum/BlockChain.h
            src/cpp-ethereum/libethereum/BlockChainSync.cpp
            src/cpp-ethereum/libethereum/BlockChainSync.h
            src/cpp-ethereum/libethereum/BlockDetails.cpp
            src/cpp-ethereum/libethereum/BlockDetails.h
            src/cpp-ethereum/libethereum/BlockQueue.cpp
            src/cpp-ethereum/libethereum/BlockQueue.h
            src/cpp-ethereum/libethereum/ChainParams.cpp
            src/cpp-ethereum/libethereum/ChainParams.h
            src/cpp-ethereum/libethereum/Client.cpp
            src/cpp-ethereum/libethereum/Client.h
            src/cpp-ethereum/libethereum/ClientBase.cpp
            src/cpp-ethereum/libethereum/ClientBase.h
            src/cpp-ethereum/libethereum/ClientTest.cpp
            src/cpp-ethereum/libethereum/ClientTest.h
            src/cpp-ethereum/libethereum/CodeSizeCache.h
            src/cpp-ethereum/libethereum/CommonNet.cpp
            src/cpp-ethereum/libethereum/CommonNet.h
            src/cpp-ethereum/libethereum/Defaults.cpp
            src/cpp-ethereum/libethereum/Defaults.h
            src/cpp-ethereum/libethereum/EthereumHost.cpp
            src/cpp-ethereum/libethereum/EthereumHost.h
            src/cpp-ethereum/libethereum/EthereumPeer.cpp
            src/cpp-ethereum/libethereum/EthereumPeer.h
            src/cpp-ethereum/libethereum/Executive.cpp
            src/cpp-ethereum/libethereum/Executive.h
            src/cpp-ethereum/libethereum/ExtVM.cpp
            src/cpp-ethereum/libethereum/ExtVM.h
            src/cpp-ethereum/libethereum/GasPricer.cpp
            src/cpp-ethereum/libethereum/GasPricer.h
            src/cpp-ethereum/libethereum/GenericFarm.h
            src/cpp-ethereum/libethereum/GenericMiner.h
            src/cpp-ethereum/libethereum/GenesisInfo.cpp
            src/cpp-ethereum/libethereum/GenesisInfo.h
            src/cpp-ethereum/libethereum/Interface.cpp
            src/cpp-ethereum/libethereum/Interface.h
            src/cpp-ethereum/libethereum/LogFilter.cpp
            src/cpp-ethereum/libethereum/LogFilter.h
            src/cpp-ethereum/libethereum/MiningClient.cpp
            src/cpp-ethereum/libethereum/MiningClient.h
            src/cpp-ethereum/libethereum/State.cpp
            src/cpp-ethereum/libethereum/State.h
            src/cpp-ethereum/libethereum/Transaction.cpp
            src/cpp-ethereum/libethereum/Transaction.h
            src/cpp-ethereum/libethereum/TransactionQueue.cpp
            src/cpp-ethereum/libethereum/TransactionQueue.h
            src/cpp-ethereum/libethereum/TransactionReceipt.cpp
            src/cpp-ethereum/libethereum/TransactionReceipt.h
            src/cpp-ethereum/libethereum/VerifiedBlock.h
            src/cpp-ethereum/libevm/All.h
            src/cpp-ethereum/libevm/ExtVMFace.cpp
            src/cpp-ethereum/libevm/ExtVMFace.h
            src/cpp-ethereum/libevm/JitVM.cpp
            src/cpp-ethereum/libevm/JitVM.h
            src/cpp-ethereum/libevm/SmartVM.cpp
            src/cpp-ethereum/libevm/SmartVM.h
            src/cpp-ethereum/libevm/VM.cpp
            src/cpp-ethereum/libevm/VM.h
            src/cpp-ethereum/libevm/VMCalls.cpp
            src/cpp-ethereum/libevm/VMConfig.h
            src/cpp-ethereum/libevm/VMFace.h
            src/cpp-ethereum/libevm/VMFactory.cpp
            src/cpp-ethereum/libevm/VMFactory.h
            src/cpp-ethereum/libevm/VMOpt.cpp
            src/cpp-ethereum/libevm/VMValidate.cpp
            src/cpp-ethereum/libevmcore/EVMSchedule.h
            src/cpp-ethereum/libevmcore/Exceptions.h
            src/cpp-ethereum/libevmcore/Instruction.cpp
            src/cpp-ethereum/libevmcore/Instruction.h
            src/cpp-ethereum/libp2p/All.h
            src/cpp-ethereum/libp2p/Capability.cpp
            src/cpp-ethereum/libp2p/Capability.h
            src/cpp-ethereum/libp2p/Common.cpp
            src/cpp-ethereum/libp2p/Common.h
            src/cpp-ethereum/libp2p/Host.cpp
            src/cpp-ethereum/libp2p/Host.h
            src/cpp-ethereum/libp2p/HostCapability.cpp
            src/cpp-ethereum/libp2p/HostCapability.h
            src/cpp-ethereum/libp2p/Network.cpp
            src/cpp-ethereum/libp2p/Network.h
            src/cpp-ethereum/libp2p/NodeTable.cpp
            src/cpp-ethereum/libp2p/NodeTable.h
            src/cpp-ethereum/libp2p/Peer.cpp
            src/cpp-ethereum/libp2p/Peer.h
            src/cpp-ethereum/libp2p/RLPXFrameCoder.cpp
            src/cpp-ethereum/libp2p/RLPXFrameCoder.h
            src/cpp-ethereum/libp2p/RLPXFrameReader.cpp
            src/cpp-ethereum/libp2p/RLPXFrameReader.h
            src/cpp-ethereum/libp2p/RLPXFrameWriter.cpp
            src/cpp-ethereum/libp2p/RLPXFrameWriter.h
            src/cpp-ethereum/libp2p/RLPxHandshake.cpp
            src/cpp-ethereum/libp2p/RLPxHandshake.h
            src/cpp-ethereum/libp2p/RLPXPacket.h
            src/cpp-ethereum/libp2p/RLPXSocket.h
            src/cpp-ethereum/libp2p/RLPXSocketIO.cpp
            src/cpp-ethereum/libp2p/RLPXSocketIO.h
            src/cpp-ethereum/libp2p/Session.cpp
            src/cpp-ethereum/libp2p/Session.h
            src/cpp-ethereum/libp2p/UDP.cpp
            src/cpp-ethereum/libp2p/UDP.h
            src/cpp-ethereum/libp2p/UPnP.cpp
            src/cpp-ethereum/libp2p/UPnP.h
            src/cpp-ethereum/libwebthree/WebThree.cpp
            src/cpp-ethereum/libwebthree/WebThree.h
            src/cpp-ethereum/libwhisper/BloomFilter.h
            src/cpp-ethereum/libwhisper/Common.cpp
            src/cpp-ethereum/libwhisper/Common.h
            src/cpp-ethereum/libwhisper/Interface.cpp
            src/cpp-ethereum/libwhisper/Interface.h
            src/cpp-ethereum/libwhisper/Message.cpp
            src/cpp-ethereum/libwhisper/Message.h
            src/cpp-ethereum/libwhisper/WhisperDB.cpp
            src/cpp-ethereum/libwhisper/WhisperDB.h
            src/cpp-ethereum/libwhisper/WhisperHost.cpp
            src/cpp-ethereum/libwhisper/WhisperHost.h
            src/cpp-ethereum/libwhisper/WhisperPeer.cpp
            src/cpp-ethereum/libwhisper/WhisperPeer.h
            src/cpp-ethereum/rlp/main.cpp
            src/cpp-ethereum/utils/json_spirit/JsonSpiritHeaders.h
            src/cpp-ethereum/utils/json_spirit/json_spirit.h
            src/cpp-ethereum/utils/json_spirit/json_spirit_error_position.h
            src/cpp-ethereum/utils/json_spirit/json_spirit_reader.cpp
            src/cpp-ethereum/utils/json_spirit/json_spirit_reader.h
            src/cpp-ethereum/utils/json_spirit/json_spirit_reader_template.h
            src/cpp-ethereum/utils/json_spirit/json_spirit_stream_reader.h
            src/cpp-ethereum/utils/json_spirit/json_spirit_utils.h
            src/cpp-ethereum/utils/json_spirit/json_spirit_value.cpp
            src/cpp-ethereum/utils/json_spirit/json_spirit_value.h
            src/cpp-ethereum/utils/json_spirit/json_spirit_writer.cpp
            src/cpp-ethereum/utils/json_spirit/json_spirit_writer.h
            src/cpp-ethereum/utils/json_spirit/json_spirit_writer_template.h
            src/cpp-ethereum/utils/libscrypt/b64.c
            src/cpp-ethereum/utils/libscrypt/b64.h
            src/cpp-ethereum/utils/libscrypt/crypto-mcf.c
            src/cpp-ethereum/utils/libscrypt/crypto-scrypt-saltgen.c
            src/cpp-ethereum/utils/libscrypt/crypto_scrypt-check.c
            src/cpp-ethereum/utils/libscrypt/crypto_scrypt-hexconvert.c
            src/cpp-ethereum/utils/libscrypt/crypto_scrypt-hexconvert.h
            src/cpp-ethereum/utils/libscrypt/crypto_scrypt-nosse.c
            src/cpp-ethereum/utils/libscrypt/libscrypt.h
            src/cpp-ethereum/utils/libscrypt/sha256.c
            src/cpp-ethereum/utils/libscrypt/sha256.h
            src/cpp-ethereum/utils/libscrypt/slowequals.c
            src/cpp-ethereum/utils/libscrypt/slowequals.h
            src/cpp-ethereum/utils/libscrypt/sysendian.h
            src/crypter.cpp
            src/crypter.h
            src/crypto/aes_helper.c
            src/crypto/common.h
            src/crypto/cubehash.c
            src/crypto/echo.c
            src/crypto/fugue.c
            src/crypto/gost.c
            src/crypto/hmac_sha256.cpp
            src/crypto/hmac_sha256.h
            src/crypto/hmac_sha512.cpp
            src/crypto/hmac_sha512.h
            src/crypto/jh.c
            src/crypto/lyra2/Lyra2.c
            src/crypto/lyra2/Lyra2.h
            src/crypto/lyra2/Sponge.c
            src/crypto/lyra2/Sponge.h
            src/crypto/rfc6979_hmac_sha256.cpp
            src/crypto/rfc6979_hmac_sha256.h
            src/crypto/ripemd160.cpp
            src/crypto/ripemd160.h
            src/crypto/scrypt.cpp
            src/crypto/scrypt.h
            src/crypto/sha1.cpp
            src/crypto/sha1.h
            src/crypto/sha256.cpp
            src/crypto/sha256.h
            src/crypto/sha256_sse4.cpp
            src/crypto/sha512.cpp
            src/crypto/sha512.h
            src/crypto/skein.c
            src/crypto/sph_cubehash.h
            src/crypto/sph_echo.h
            src/crypto/sph_fugue.h
            src/crypto/sph_gost.h
            src/crypto/sph_jh.h
            src/crypto/sph_skein.h
            src/crypto/sph_types.h
            src/cryptopp/3way.cpp
            src/cryptopp/3way.h
            src/cryptopp/adler32.cpp
            src/cryptopp/adler32.h
            src/cryptopp/aes.h
            src/cryptopp/algebra.cpp
            src/cryptopp/algebra.h
            src/cryptopp/algparam.cpp
            src/cryptopp/algparam.h
            src/cryptopp/arc4.cpp
            src/cryptopp/arc4.h
            src/cryptopp/argnames.h
            src/cryptopp/asn.cpp
            src/cryptopp/asn.h
            src/cryptopp/authenc.cpp
            src/cryptopp/authenc.h
            src/cryptopp/base32.cpp
            src/cryptopp/base32.h
            src/cryptopp/base64.cpp
            src/cryptopp/base64.h
            src/cryptopp/basecode.cpp
            src/cryptopp/basecode.h
            src/cryptopp/bench.h
            src/cryptopp/bench1.cpp
            src/cryptopp/bench2.cpp
            src/cryptopp/bfinit.cpp
            src/cryptopp/blake2.cpp
            src/cryptopp/blake2.h
            src/cryptopp/blowfish.cpp
            src/cryptopp/blowfish.h
            src/cryptopp/blumshub.cpp
            src/cryptopp/blumshub.h
            src/cryptopp/camellia.cpp
            src/cryptopp/camellia.h
            src/cryptopp/cast.cpp
            src/cryptopp/cast.h
            src/cryptopp/casts.cpp
            src/cryptopp/cbcmac.cpp
            src/cryptopp/cbcmac.h
            src/cryptopp/ccm.cpp
            src/cryptopp/ccm.h
            src/cryptopp/chacha.cpp
            src/cryptopp/chacha.h
            src/cryptopp/channels.cpp
            src/cryptopp/channels.h
            src/cryptopp/cmac.cpp
            src/cryptopp/cmac.h
            src/cryptopp/config.h
            src/cryptopp/cpu.cpp
            src/cryptopp/cpu.h
            src/cryptopp/crc.cpp
            src/cryptopp/crc.h
            src/cryptopp/cryptlib.cpp
            src/cryptopp/cryptlib.h
            src/cryptopp/datatest.cpp
            src/cryptopp/default.cpp
            src/cryptopp/default.h
            src/cryptopp/des.cpp
            src/cryptopp/des.h
            src/cryptopp/dessp.cpp
            src/cryptopp/dh.cpp
            src/cryptopp/dh.h
            src/cryptopp/dh2.cpp
            src/cryptopp/dh2.h
            src/cryptopp/dll.cpp
            src/cryptopp/dll.h
            src/cryptopp/dlltest.cpp
            src/cryptopp/dmac.h
            src/cryptopp/drbg.h
            src/cryptopp/dsa.cpp
            src/cryptopp/dsa.h
            src/cryptopp/eax.cpp
            src/cryptopp/eax.h
            src/cryptopp/ec2n.cpp
            src/cryptopp/ec2n.h
            src/cryptopp/eccrypto.cpp
            src/cryptopp/eccrypto.h
            src/cryptopp/ecp.cpp
            src/cryptopp/ecp.h
            src/cryptopp/ecpoint.h
            src/cryptopp/elgamal.cpp
            src/cryptopp/elgamal.h
            src/cryptopp/emsa2.cpp
            src/cryptopp/emsa2.h
            src/cryptopp/eprecomp.cpp
            src/cryptopp/eprecomp.h
            src/cryptopp/esign.cpp
            src/cryptopp/esign.h
            src/cryptopp/factory.h
            src/cryptopp/fhmqv.h
            src/cryptopp/files.cpp
            src/cryptopp/files.h
            src/cryptopp/filters.cpp
            src/cryptopp/filters.h
            src/cryptopp/fips140.cpp
            src/cryptopp/fips140.h
            src/cryptopp/fipsalgt.cpp
            src/cryptopp/fipstest.cpp
            src/cryptopp/fltrimpl.h
            src/cryptopp/gcm.cpp
            src/cryptopp/gcm.h
            src/cryptopp/gf256.cpp
            src/cryptopp/gf256.h
            src/cryptopp/gf2n.cpp
            src/cryptopp/gf2n.h
            src/cryptopp/gf2_32.cpp
            src/cryptopp/gf2_32.h
            src/cryptopp/gfpcrypt.cpp
            src/cryptopp/gfpcrypt.h
            src/cryptopp/gost.cpp
            src/cryptopp/gost.h
            src/cryptopp/gzip.cpp
            src/cryptopp/gzip.h
            src/cryptopp/hex.cpp
            src/cryptopp/hex.h
            src/cryptopp/hkdf.h
            src/cryptopp/hmac.cpp
            src/cryptopp/hmac.h
            src/cryptopp/hmqv.h
            src/cryptopp/hrtimer.cpp
            src/cryptopp/hrtimer.h
            src/cryptopp/ida.cpp
            src/cryptopp/ida.h
            src/cryptopp/idea.cpp
            src/cryptopp/idea.h
            src/cryptopp/integer.cpp
            src/cryptopp/integer.h
            src/cryptopp/iterhash.cpp
            src/cryptopp/iterhash.h
            src/cryptopp/keccak.cpp
            src/cryptopp/keccak.h
            src/cryptopp/lubyrack.h
            src/cryptopp/luc.cpp
            src/cryptopp/luc.h
            src/cryptopp/mars.cpp
            src/cryptopp/mars.h
            src/cryptopp/marss.cpp
            src/cryptopp/md2.cpp
            src/cryptopp/md2.h
            src/cryptopp/md4.cpp
            src/cryptopp/md4.h
            src/cryptopp/md5.cpp
            src/cryptopp/md5.h
            src/cryptopp/mdc.h
            src/cryptopp/mersenne.h
            src/cryptopp/misc.cpp
            src/cryptopp/misc.h
            src/cryptopp/modarith.h
            src/cryptopp/modes.cpp
            src/cryptopp/modes.h
            src/cryptopp/modexppc.h
            src/cryptopp/mqueue.cpp
            src/cryptopp/mqueue.h
            src/cryptopp/mqv.cpp
            src/cryptopp/mqv.h
            src/cryptopp/nbtheory.cpp
            src/cryptopp/nbtheory.h
            src/cryptopp/network.cpp
            src/cryptopp/network.h
            src/cryptopp/nr.h
            src/cryptopp/oaep.cpp
            src/cryptopp/oaep.h
            src/cryptopp/oids.h
            src/cryptopp/osrng.cpp
            src/cryptopp/osrng.h
            src/cryptopp/ossig.h
            src/cryptopp/panama.cpp
            src/cryptopp/panama.h
            src/cryptopp/pch.cpp
            src/cryptopp/pch.h
            src/cryptopp/pkcspad.cpp
            src/cryptopp/pkcspad.h
            src/cryptopp/poly1305.cpp
            src/cryptopp/poly1305.h
            src/cryptopp/polynomi.cpp
            src/cryptopp/polynomi.h
            src/cryptopp/pssr.cpp
            src/cryptopp/pssr.h
            src/cryptopp/pubkey.cpp
            src/cryptopp/pubkey.h
            src/cryptopp/pwdbased.h
            src/cryptopp/queue.cpp
            src/cryptopp/queue.h
            src/cryptopp/rabin.cpp
            src/cryptopp/rabin.h
            src/cryptopp/randpool.cpp
            src/cryptopp/randpool.h
            src/cryptopp/rc2.cpp
            src/cryptopp/rc2.h
            src/cryptopp/rc5.cpp
            src/cryptopp/rc5.h
            src/cryptopp/rc6.cpp
            src/cryptopp/rc6.h
            src/cryptopp/rdrand.cpp
            src/cryptopp/rdrand.h
            src/cryptopp/rdtables.cpp
            src/cryptopp/regtest.cpp
            src/cryptopp/resource.h
            src/cryptopp/rijndael.cpp
            src/cryptopp/rijndael.h
            src/cryptopp/ripemd.cpp
            src/cryptopp/ripemd.h
            src/cryptopp/rng.cpp
            src/cryptopp/rng.h
            src/cryptopp/rsa.cpp
            src/cryptopp/rsa.h
            src/cryptopp/rw.cpp
            src/cryptopp/rw.h
            src/cryptopp/safer.cpp
            src/cryptopp/safer.h
            src/cryptopp/salsa.cpp
            src/cryptopp/salsa.h
            src/cryptopp/seal.cpp
            src/cryptopp/seal.h
            src/cryptopp/secblock.h
            src/cryptopp/seckey.h
            src/cryptopp/seed.cpp
            src/cryptopp/seed.h
            src/cryptopp/serpent.cpp
            src/cryptopp/serpent.h
            src/cryptopp/serpentp.h
            src/cryptopp/sha.cpp
            src/cryptopp/sha.h
            src/cryptopp/sha3.cpp
            src/cryptopp/sha3.h
            src/cryptopp/shacal2.cpp
            src/cryptopp/shacal2.h
            src/cryptopp/shark.cpp
            src/cryptopp/shark.h
            src/cryptopp/sharkbox.cpp
            src/cryptopp/simple.cpp
            src/cryptopp/simple.h
            src/cryptopp/siphash.h
            src/cryptopp/skipjack.cpp
            src/cryptopp/skipjack.h
            src/cryptopp/smartptr.h
            src/cryptopp/socketft.cpp
            src/cryptopp/socketft.h
            src/cryptopp/sosemanuk.cpp
            src/cryptopp/sosemanuk.h
            src/cryptopp/square.cpp
            src/cryptopp/square.h
            src/cryptopp/squaretb.cpp
            src/cryptopp/stdcpp.h
            src/cryptopp/strciphr.cpp
            src/cryptopp/strciphr.h
            src/cryptopp/tea.cpp
            src/cryptopp/tea.h
            src/cryptopp/test.cpp
            src/cryptopp/TestScripts/cryptest-coverity.cpp
            src/cryptopp/tftables.cpp
            src/cryptopp/tiger.cpp
            src/cryptopp/tiger.h
            src/cryptopp/tigertab.cpp
            src/cryptopp/trap.h
            src/cryptopp/trdlocal.cpp
            src/cryptopp/trdlocal.h
            src/cryptopp/trunhash.h
            src/cryptopp/ttmac.cpp
            src/cryptopp/ttmac.h
            src/cryptopp/twofish.cpp
            src/cryptopp/twofish.h
            src/cryptopp/validat0.cpp
            src/cryptopp/validat1.cpp
            src/cryptopp/validat2.cpp
            src/cryptopp/validat3.cpp
            src/cryptopp/validate.h
            src/cryptopp/vmac.cpp
            src/cryptopp/vmac.h
            src/cryptopp/wait.cpp
            src/cryptopp/wait.h
            src/cryptopp/wake.cpp
            src/cryptopp/wake.h
            src/cryptopp/whrlpool.cpp
            src/cryptopp/whrlpool.h
            src/cryptopp/winpipes.cpp
            src/cryptopp/winpipes.h
            src/cryptopp/words.h
            src/cryptopp/xtr.cpp
            src/cryptopp/xtr.h
            src/cryptopp/xtrcrypt.cpp
            src/cryptopp/xtrcrypt.h
            src/cryptopp/zdeflate.cpp
            src/cryptopp/zdeflate.h
            src/cryptopp/zinflate.cpp
            src/cryptopp/zinflate.h
            src/cryptopp/zlib.cpp
            src/cryptopp/zlib.h
            src/cuckoocache.h
            src/darksend.cpp
            src/darksend.h
            src/db.cpp
            src/db.h
            src/eccryptoverify.cpp
            src/eccryptoverify.h
            src/ecwrapper.cpp
            src/ecwrapper.h
            src/hash.cpp
            src/hash.h
            src/hashblock.h
            src/hdchain.cpp
            src/hdchain.h
            src/httprpc.cpp
            src/httprpc.h
            src/httpserver.cpp
            src/httpserver.h
            src/indirectmap.h
            src/init.cpp
            src/init.h
            src/instantx.cpp
            src/instantx.h
            src/json/allocator.h
            src/json/assertions.h
            src/json/autolink.h
            src/json/config.h
            src/json/features.h
            src/json/forwards.h
            src/json/json.h
            src/json/json_spirit.h
            src/json/json_spirit_error_position.h
            src/json/json_spirit_reader.cpp
            src/json/json_spirit_reader.h
            src/json/json_spirit_reader_template.h
            src/json/json_spirit_stream_reader.h
            src/json/json_spirit_utils.h
            src/json/json_spirit_value.cpp
            src/json/json_spirit_value.h
            src/json/json_spirit_writer.cpp
            src/json/json_spirit_writer.h
            src/json/json_spirit_writer_template.h
            src/json/reader.h
            src/json/value.h
            src/json/version.h
            src/json/writer.h
            src/key.cpp
            src/key.h
            src/keystore.cpp
            src/keystore.h
            src/leveldb/db/builder.h
            src/leveldb/db/c_test.c
            src/leveldb/db/dbformat.h
            src/leveldb/db/db_impl.h
            src/leveldb/db/db_iter.h
            src/leveldb/db/filename.h
            src/leveldb/db/log_format.h
            src/leveldb/db/log_reader.h
            src/leveldb/db/log_writer.h
            src/leveldb/db/memtable.h
            src/leveldb/db/skiplist.h
            src/leveldb/db/snapshot.h
            src/leveldb/db/table_cache.h
            src/leveldb/db/version_edit.h
            src/leveldb/db/version_set.h
            src/leveldb/db/write_batch_internal.h
            src/leveldb/helpers/memenv/memenv.h
            src/leveldb/include/leveldb/c.h
            src/leveldb/include/leveldb/cache.h
            src/leveldb/include/leveldb/comparator.h
            src/leveldb/include/leveldb/db.h
            src/leveldb/include/leveldb/dumpfile.h
            src/leveldb/include/leveldb/env.h
            src/leveldb/include/leveldb/filter_policy.h
            src/leveldb/include/leveldb/iterator.h
            src/leveldb/include/leveldb/options.h
            src/leveldb/include/leveldb/slice.h
            src/leveldb/include/leveldb/status.h
            src/leveldb/include/leveldb/table.h
            src/leveldb/include/leveldb/table_builder.h
            src/leveldb/include/leveldb/write_batch.h
            src/leveldb/port/atomic_pointer.h
            src/leveldb/port/port.h
            src/leveldb/port/port_example.h
            src/leveldb/port/port_posix.h
            src/leveldb/port/port_win.h
            src/leveldb/port/thread_annotations.h
            src/leveldb/port/win/stdint.h
            src/leveldb/table/block.h
            src/leveldb/table/block_builder.h
            src/leveldb/table/filter_block.h
            src/leveldb/table/format.h
            src/leveldb/table/iterator_wrapper.h
            src/leveldb/table/merger.h
            src/leveldb/table/two_level_iterator.h
            src/leveldb/util/arena.h
            src/leveldb/util/coding.h
            src/leveldb/util/crc32c.h
            src/leveldb/util/hash.h
            src/leveldb/util/histogram.h
            src/leveldb/util/logging.h
            src/leveldb/util/mutexlock.h
            src/leveldb/util/posix_logger.h
            src/leveldb/util/random.h
            src/leveldb/util/testharness.h
            src/leveldb/util/testutil.h
            src/leveldbwrapper.cpp
            src/leveldbwrapper.h
            src/limitedmap.h
            src/lux/luxDGP.cpp
            src/lux/luxDGP.h
            src/lux/luxstate.cpp
            src/lux/luxstate.h
            src/lux/luxtransaction.h
            src/lux/storageresults.cpp
            src/lux/storageresults.h
            src/lux-cli.cpp
            src/lux-tx.cpp
            src/luxcontrol.cpp
            src/luxcontrol.h
            src/luxd.cpp
            src/luxgate/atomicswap.cpp
            src/luxgate/atomicswap.h
            src/luxgate/bitcoinclient.cpp
            src/luxgate/bitcoinclient.h
            src/luxgate/blockchainclient.cpp
            src/luxgate/blockchainclient.h
            src/luxgate/context.h
            src/luxgate/http.cpp
            src/luxgate/http.h
            src/luxgate/lgconfig.cpp
            src/luxgate/lgconfig.h
            src/luxgate/luxclient.cpp
            src/luxgate/luxclient.h
            src/luxgate/luxgate.cpp
            src/luxgate/luxgate.h
            src/luxgate/logwriter.h
            src/luxgate/market.cpp
            src/luxgate/market.h
            src/luxgate/order.cpp
            src/luxgate/order.h
            src/luxgate/orderbook.cpp
            src/luxgate/orderbook.h
            src/luxgate/rpcluxgate.cpp
            src/luxgate/sql/sqlite3.c
            src/luxgate/sql/sqlite3.h
            src/luxgate/storage.cpp
            src/luxgate/storage.h
            src/luxgate/test/test_luxgate.cpp
            src/luxgate/test/unspent_output_generator.cpp
            src/luxgate/test/unspent_output_generator.h
            src/luxgate/version.h
            src/luxgate/zmqsub.cpp
            src/luxgate/zmqsub.h
            src/main.cpp
            src/main.h
            src/masternode.cpp
            src/masternode.h
            src/masternodeconfig.cpp
            src/masternodeconfig.h
            src/memenv.h
            src/memusage.h
            src/merkleblock.cpp
            src/merkleblock.h
            src/miner.cpp
            src/miner.h
            src/mruset.h
            src/net.cpp
            src/net.h
            src/netbase.cpp
            src/netbase.h
            src/noui.cpp
            src/noui.h
            src/obj/build.h
            src/policy/fees.cpp
            src/policy/fees.h
            src/policy/policy.cpp
            src/policy/policy.h
            src/pow.cpp
            src/pow.h
            src/prevector.h
            src/primitives/block.cpp
            src/primitives/block.h
            src/primitives/transaction.cpp
            src/primitives/transaction.h
            src/protocol.cpp
            src/protocol.h
            src/pubkey.cpp
            src/pubkey.h
            src/qt/abifunctionfield.cpp
            src/qt/abifunctionfield.h
            src/qt/abiparam.cpp
            src/qt/abiparam.h
            src/qt/abiparamitem.cpp
            src/qt/abiparamitem.h
            src/qt/abiparamsfield.cpp
            src/qt/abiparamsfield.h
            src/qt/addeditluxnode.cpp
            src/qt/addeditluxnode.h
            src/qt/addressbookpage.cpp
            src/qt/addressbookpage.h
            src/qt/addressfield.cpp
            src/qt/addressfield.h
            src/qt/addresstablemodel.cpp
            src/qt/addresstablemodel.h
            src/qt/addtokenpage.cpp
            src/qt/addtokenpage.h
            src/qt/askpassphrasedialog.cpp
            src/qt/askpassphrasedialog.h
            src/qt/bantablemodel.cpp
            src/qt/bantablemodel.h
            src/qt/bip38tooldialog.cpp
            src/qt/bip38tooldialog.h
            src/qt/bitcoinaddressvalidator.cpp
            src/qt/bitcoinaddressvalidator.h
            src/qt/bitcoinamountfield.cpp
            src/qt/bitcoinamountfield.h
            src/qt/bitcoingui.cpp
            src/qt/bitcoingui.h
            src/qt/bitcoinunits.cpp
            src/qt/bitcoinunits.h
            src/qt/blockexplorer.cpp
            src/qt/blockexplorer.h
            src/qt/callcontract.cpp
            src/qt/callcontract.h
            src/qt/clientmodel.cpp
            src/qt/clientmodel.h
            src/qt/coincontroldialog.cpp
            src/qt/coincontroldialog.h
            src/qt/coincontroltreewidget.cpp
            src/qt/coincontroltreewidget.h
            src/qt/contractabi.cpp
            src/qt/contractabi.h
            src/qt/contractbookpage.cpp
            src/qt/contractbookpage.h
            src/qt/contractresult.cpp
            src/qt/contractresult.h
            src/qt/contracttablemodel.cpp
            src/qt/contracttablemodel.h
            src/qt/createcontract.cpp
            src/qt/createcontract.h
            src/qt/csvmodelwriter.cpp
            src/qt/csvmodelwriter.h
            src/qt/customlist.h
            src/qt/darksendconfig.cpp
            src/qt/darksendconfig.h
            src/qt/editaddressdialog.cpp
            src/qt/editaddressdialog.h
            src/qt/editcontractinfodialog.cpp
            src/qt/editcontractinfodialog.h
            src/qt/eula.cpp
            src/qt/eula.h
            src/qt/eventlog.cpp
            src/qt/eventlog.h
            src/qt/execrpccommand.cpp
            src/qt/execrpccommand.h
            src/qt/forms/ui_addeditluxnode.h
            src/qt/forms/ui_addressbookpage.h
            src/qt/forms/ui_addtokenpage.h
            src/qt/forms/ui_askpassphrasedialog.h
            src/qt/forms/ui_bip38tooldialog.h
            src/qt/forms/ui_blockexplorer.h
            src/qt/forms/ui_callcontract.h
            src/qt/forms/ui_coincontroldialog.h
            src/qt/forms/ui_contractbookpage.h
            src/qt/forms/ui_contractresult.h
            src/qt/forms/ui_createcontract.h
            src/qt/forms/ui_darksendconfig.h
            src/qt/forms/ui_editaddressdialog.h
            src/qt/forms/ui_editcontractinfodialog.h
            src/qt/forms/ui_eula.h
            src/qt/forms/ui_helpmessagedialog.h
            src/qt/forms/ui_hexaddressconverter.h
            src/qt/forms/ui_intro.h
            src/qt/forms/ui_lsrtoken.h
            src/qt/forms/ui_luxgatebidaskpanel.h
            src/qt/forms/ui_luxgateconfigpanel.h
            src/qt/forms/ui_luxgatecreateorderpanel.h
            src/qt/forms/ui_luxgatedialog.h
            src/qt/forms/ui_luxgatehistorypanel.h
            src/qt/forms/ui_luxgateopenorderspanel.h
            src/qt/forms/ui_luxgateorderbookpanel.h
            src/qt/forms/ui_luxnodeconfigdialog.h
            src/qt/forms/ui_masternodemanager.h
            src/qt/forms/ui_modaloverlay.h
            src/qt/forms/ui_multisenddialog.h
            src/qt/forms/ui_openuridialog.h
            src/qt/forms/ui_optionsdialog.h
            src/qt/forms/ui_overviewpage.h
            src/qt/forms/ui_receivecoinsdialog.h
            src/qt/forms/ui_receiverequestdialog.h
            src/qt/forms/ui_receivetokenpage.h
            src/qt/forms/ui_restoredialog.h
            src/qt/forms/ui_rpcconsole.h
            src/qt/forms/ui_sendcoinsdialog.h
            src/qt/forms/ui_sendcoinsentry.h
            src/qt/forms/ui_sendtocontract.h
            src/qt/forms/ui_sendtokenpage.h
            src/qt/forms/ui_signverifymessagedialog.h
            src/qt/forms/ui_smartcontract.h
            src/qt/forms/ui_tokendescdialog.h
            src/qt/forms/ui_tradingplot.h
            src/qt/forms/ui_transactiondescdialog.h
            src/qt/guiconstants.h
            src/qt/guiutil.cpp
            src/qt/guiutil.h
            src/qt/hexaddressconverter.cpp
            src/qt/hexaddressconverter.h
            src/qt/intro.cpp
            src/qt/intro.h
            src/qt/lsrtoken.cpp
            src/qt/lsrtoken.h
            src/qt/lux.cpp
            src/qt/luxgatebidaskpanel.cpp
            src/qt/luxgatebidaskpanel.h
            src/qt/luxgatebidsasksmodel.cpp
            src/qt/luxgatebidsasksmodel.h
            src/qt/luxgateconfigmodel.cpp
            src/qt/luxgateconfigmodel.h
            src/qt/luxgateconfigpanel.cpp
            src/qt/luxgateconfigpanel.h
            src/qt/luxgatecreateorderpanel.cpp
            src/qt/luxgatecreateorderpanel.h
            src/qt/luxgatedialog.cpp
            src/qt/luxgatedialog.h
            src/qt/luxgategui_global.cpp
            src/qt/luxgategui_global.h
            src/qt/luxgatehistorymodel.cpp
            src/qt/luxgatehistorymodel.h
            src/qt/luxgatehistorypanel.cpp
            src/qt/luxgatehistorypanel.h
            src/qt/luxgateopenordersmodel.cpp
            src/qt/luxgateopenordersmodel.h
            src/qt/luxgateopenorderspanel.cpp
            src/qt/luxgateopenorderspanel.h
            src/qt/luxgateorderbookpanel.cpp
            src/qt/luxgateorderbookpanel.h
            src/qt/luxgateorderview.cpp
            src/qt/luxgateorderview.h
            src/qt/luxgatepricedelegate.cpp
            src/qt/luxgatepricedelegate.h
            src/qt/luxgatetableview.cpp
            src/qt/luxgatetableview.h
            src/qt/luxnodeconfigdialog.cpp
            src/qt/luxnodeconfigdialog.h
            src/qt/luxsendconfig.cpp
            src/qt/luxsendconfig.h
            src/qt/luxstrings.cpp
            src/qt/macdockiconhandler.h
            src/qt/macnotificationhandler.h
            src/qt/masternodemanager.cpp
            src/qt/masternodemanager.h
            src/qt/moc_abifunctionfield.cpp
            src/qt/moc_abiparam.cpp
            src/qt/moc_abiparamitem.cpp
            src/qt/moc_abiparamsfield.cpp
            src/qt/moc_addeditluxnode.cpp
            src/qt/moc_addressbookpage.cpp
            src/qt/moc_addressfield.cpp
            src/qt/moc_addresstablemodel.cpp
            src/qt/moc_addtokenpage.cpp
            src/qt/moc_askpassphrasedialog.cpp
            src/qt/moc_bantablemodel.cpp
            src/qt/moc_bip38tooldialog.cpp
            src/qt/moc_bitcoinaddressvalidator.cpp
            src/qt/moc_bitcoinamountfield.cpp
            src/qt/moc_bitcoingui.cpp
            src/qt/moc_bitcoinunits.cpp
            src/qt/moc_blockexplorer.cpp
            src/qt/moc_callcontract.cpp
            src/qt/moc_clientmodel.cpp
            src/qt/moc_coincontroldialog.cpp
            src/qt/moc_coincontroltreewidget.cpp
            src/qt/moc_contractbookpage.cpp
            src/qt/moc_contractresult.cpp
            src/qt/moc_contracttablemodel.cpp
            src/qt/moc_createcontract.cpp
            src/qt/moc_csvmodelwriter.cpp
            src/qt/moc_darksendconfig.cpp
            src/qt/moc_editaddressdialog.cpp
            src/qt/moc_editcontractinfodialog.cpp
            src/qt/moc_eula.cpp
            src/qt/moc_guiutil.cpp
            src/qt/moc_hexaddressconverter.cpp
            src/qt/moc_intro.cpp
            src/qt/moc_lsrtoken.cpp
            src/qt/moc_luxgatebidaskpanel.cpp
            src/qt/moc_luxgatebidsasksmodel.cpp
            src/qt/moc_luxgateconfigmodel.cpp
            src/qt/moc_luxgateconfigpanel.cpp
            src/qt/moc_luxgatecreateorderpanel.cpp
            src/qt/moc_luxgatedialog.cpp
            src/qt/moc_luxgatehistorymodel.cpp
            src/qt/moc_luxgatehistorypanel.cpp
            src/qt/moc_luxgateopenordersmodel.cpp
            src/qt/moc_luxgateopenorderspanel.cpp
            src/qt/moc_luxgateorderbookpanel.cpp
            src/qt/moc_luxgatepricedelegate.cpp
            src/qt/moc_luxgatetableview.cpp
            src/qt/moc_luxnodeconfigdialog.cpp
            src/qt/moc_macdockiconhandler.cpp
            src/qt/moc_macnotificationhandler.cpp
            src/qt/moc_masternodemanager.cpp
            src/qt/moc_modaloverlay.cpp
            src/qt/moc_multisenddialog.cpp
            src/qt/moc_notificator.cpp
            src/qt/moc_openuridialog.cpp
            src/qt/moc_optionsdialog.cpp
            src/qt/moc_optionsmodel.cpp
            src/qt/moc_overviewpage.cpp
            src/qt/moc_paymentserver.cpp
            src/qt/moc_peertablemodel.cpp
            src/qt/moc_qcustomplot.cpp
            src/qt/moc_qvalidatedlineedit.cpp
            src/qt/moc_qvalidatedtextedit.cpp
            src/qt/moc_qvaluecombobox.cpp
            src/qt/moc_receivecoinsdialog.cpp
            src/qt/moc_receiverequestdialog.cpp
            src/qt/moc_receivetokenpage.cpp
            src/qt/moc_recentrequeststablemodel.cpp
            src/qt/moc_restoredialog.cpp
            src/qt/moc_rpcconsole.cpp
            src/qt/moc_sendcoinsdialog.cpp
            src/qt/moc_sendcoinsentry.cpp
            src/qt/moc_sendtocontract.cpp
            src/qt/moc_sendtokenpage.cpp
            src/qt/moc_signverifymessagedialog.cpp
            src/qt/moc_smartcontract.cpp
            src/qt/moc_splashscreen.cpp
            src/qt/moc_tabbarinfo.cpp
            src/qt/moc_tokenamountfield.cpp
            src/qt/moc_tokendescdialog.cpp
            src/qt/moc_tokenfilterproxy.cpp
            src/qt/moc_tokenitemmodel.cpp
            src/qt/moc_tokentransactiondesc.cpp
            src/qt/moc_tokentransactiontablemodel.cpp
            src/qt/moc_tokentransactionview.cpp
            src/qt/moc_tradingplot.cpp
            src/qt/moc_trafficgraphwidget.cpp
            src/qt/moc_transactiondesc.cpp
            src/qt/moc_transactiondescdialog.cpp
            src/qt/moc_transactionfilterproxy.cpp
            src/qt/moc_transactiontablemodel.cpp
            src/qt/moc_transactionview.cpp
            src/qt/moc_updatedialog.cpp
            src/qt/moc_utilitydialog.cpp
            src/qt/moc_walletframe.cpp
            src/qt/moc_walletmodel.cpp
            src/qt/moc_walletview.cpp
            src/qt/modaloverlay.cpp
            src/qt/modaloverlay.h
            src/qt/multisenddialog.cpp
            src/qt/multisenddialog.h
            src/qt/networkstyle.cpp
            src/qt/networkstyle.h
            src/qt/notificator.cpp
            src/qt/notificator.h
            src/qt/openuridialog.cpp
            src/qt/openuridialog.h
            src/qt/optionsdialog.cpp
            src/qt/optionsdialog.h
            src/qt/optionsmodel.cpp
            src/qt/optionsmodel.h
            src/qt/overviewpage.cpp
            src/qt/overviewpage.h
            src/qt/paymentrequest.pb.h
            src/qt/paymentrequestplus.cpp
            src/qt/paymentrequestplus.h
            src/qt/paymentserver.cpp
            src/qt/paymentserver.h
            src/qt/peertablemodel.cpp
            src/qt/peertablemodel.h
            src/qt/platformstyle.cpp
            src/qt/platformstyle.h
            src/qt/qcustomplot.cpp
            src/qt/qcustomplot.h
            src/qt/qrc_lux.cpp
            src/qt/qrc_lux_locale.cpp
            src/qt/qvalidatedlineedit.cpp
            src/qt/qvalidatedlineedit.h
            src/qt/qvalidatedtextedit.cpp
            src/qt/qvalidatedtextedit.h
            src/qt/qvaluecombobox.cpp
            src/qt/qvaluecombobox.h
            src/qt/receivecoinsdialog.cpp
            src/qt/receivecoinsdialog.h
            src/qt/receiverequestdialog.cpp
            src/qt/receiverequestdialog.h
            src/qt/receivetokenpage.cpp
            src/qt/receivetokenpage.h
            src/qt/recentrequeststablemodel.cpp
            src/qt/recentrequeststablemodel.h
            src/qt/restoredialog.cpp
            src/qt/restoredialog.h
            src/qt/rpcconsole.cpp
            src/qt/rpcconsole.h
            src/qt/sendcoinsdialog.cpp
            src/qt/sendcoinsdialog.h
            src/qt/sendcoinsentry.cpp
            src/qt/sendcoinsentry.h
            src/qt/sendtocontract.cpp
            src/qt/sendtocontract.h
            src/qt/sendtokenpage.cpp
            src/qt/sendtokenpage.h
            src/qt/signverifymessagedialog.cpp
            src/qt/signverifymessagedialog.h
            src/qt/smartcontract.cpp
            src/qt/smartcontract.h
            src/qt/smartcontractpage.cpp
            src/qt/splashscreen.cpp
            src/qt/splashscreen.h
            src/qt/tabbarinfo.cpp
            src/qt/tabbarinfo.h
            src/qt/test/paymentrequestdata.h
            src/qt/test/paymentservertests.cpp
            src/qt/test/paymentservertests.h
            src/qt/test/test_main.cpp
            src/qt/test/uritests.cpp
            src/qt/test/uritests.h
            src/qt/token.cpp
            src/qt/token.h
            src/qt/tokenamountfield.cpp
            src/qt/tokenamountfield.h
            src/qt/tokendescdialog.cpp
            src/qt/tokendescdialog.h
            src/qt/tokenfilterproxy.cpp
            src/qt/tokenfilterproxy.h
            src/qt/tokenitemmodel.cpp
            src/qt/tokenitemmodel.h
            src/qt/tokenslistview.cpp
            src/qt/tokenslistview.h
            src/qt/tokentransactiondesc.cpp
            src/qt/tokentransactiondesc.h
            src/qt/tokentransactionrecord.cpp
            src/qt/tokentransactionrecord.h
            src/qt/tokentransactiontablemodel.cpp
            src/qt/tokentransactiontablemodel.h
            src/qt/tokentransactionview.cpp
            src/qt/tokentransactionview.h
            src/qt/tradingplot.cpp
            src/qt/tradingplot.h
            src/qt/trafficgraphdata.cpp
            src/qt/trafficgraphdata.h
            src/qt/trafficgraphwidget.cpp
            src/qt/trafficgraphwidget.h
            src/qt/transactiondesc.cpp
            src/qt/transactiondesc.h
            src/qt/transactiondescdialog.cpp
            src/qt/transactiondescdialog.h
            src/qt/transactionfilterproxy.cpp
            src/qt/transactionfilterproxy.h
            src/qt/transactionrecord.cpp
            src/qt/transactionrecord.h
            src/qt/transactiontablemodel.cpp
            src/qt/transactiontablemodel.h
            src/qt/transactionview.cpp
            src/qt/transactionview.h
            src/qt/updatedialog.cpp
            src/qt/updatedialog.h
            src/qt/utilitydialog.cpp
            src/qt/utilitydialog.h
            src/qt/walletframe.cpp
            src/qt/walletframe.h
            src/qt/walletmodel.cpp
            src/qt/walletmodel.h
            src/qt/walletmodeltransaction.cpp
            src/qt/walletmodeltransaction.h
            src/qt/walletview.cpp
            src/qt/walletview.h
            src/qt/winshutdownmonitor.cpp
            src/qt/winshutdownmonitor.h
            src/random.cpp
            src/random.h
            src/rbf.cpp
            src/rbf.h
            src/rest.cpp
            src/reverselock.h
            src/reverse_iterator.h
            src/rpcblockchain.cpp
            src/rpcclient.cpp
            src/rpcclient.h
            src/rpcdarksend.cpp
            src/rpcdump.cpp
            src/rpcmining.cpp
            src/rpcmisc.cpp
            src/rpcnet.cpp
            src/rpcprotocol.cpp
            src/rpcprotocol.h
            src/rpcrawtransaction.cpp
            src/rpcserver.cpp
            src/rpcserver.h
            src/rpcutil.cpp
            src/rpcutil.h
            src/rpcwallet.cpp
            src/rpcwallet.h
            src/scheduler.cpp
            src/scheduler.h
            src/script/bitcoinconsensus.cpp
            src/script/bitcoinconsensus.h
            src/script/interpreter.cpp
            src/script/interpreter.h
            src/script/script.cpp
            src/script/script.h
            src/script/script_error.cpp
            src/script/script_error.h
            src/script/sigcache.cpp
            src/script/sigcache.h
            src/script/sign.cpp
            src/script/sign.h
            src/script/standard.cpp
            src/script/standard.h
            src/secp256k1/contrib/lax_der_parsing.c
            src/secp256k1/contrib/lax_der_parsing.h
            src/secp256k1/contrib/lax_der_privatekey_parsing.c
            src/secp256k1/contrib/lax_der_privatekey_parsing.h
            src/secp256k1/include/secp256k1.h
            src/secp256k1/include/secp256k1_ecdh.h
            src/secp256k1/include/secp256k1_recovery.h
            src/secp256k1/include/secp256k1_schnorr.h
            src/secp256k1/src/basic-config.h
            src/secp256k1/src/bench.h
            src/secp256k1/src/bench_ecdh.c
            src/secp256k1/src/bench_internal.c
            src/secp256k1/src/bench_inv.c
            src/secp256k1/src/bench_recover.c
            src/secp256k1/src/bench_schnorr_verify.c
            src/secp256k1/src/bench_sign.c
            src/secp256k1/src/bench_verify.c
            src/secp256k1/src/ecdsa.h
            src/secp256k1/src/ecdsa_impl.h
            src/secp256k1/src/eckey.h
            src/secp256k1/src/eckey_impl.h
            src/secp256k1/src/ecmult.h
            src/secp256k1/src/ecmult_const.h
            src/secp256k1/src/ecmult_const_impl.h
            src/secp256k1/src/ecmult_gen.h
            src/secp256k1/src/ecmult_gen_impl.h
            src/secp256k1/src/ecmult_impl.h
            src/secp256k1/src/ecmult_static_context.h
            src/secp256k1/src/field.h
            src/secp256k1/src/field_10x26.h
            src/secp256k1/src/field_10x26_impl.h
            src/secp256k1/src/field_5x52.h
            src/secp256k1/src/field_5x52_asm_impl.h
            src/secp256k1/src/field_5x52_impl.h
            src/secp256k1/src/field_5x52_int128_impl.h
            src/secp256k1/src/field_gmp.h
            src/secp256k1/src/field_gmp_impl.h
            src/secp256k1/src/field_impl.h
            src/secp256k1/src/gen_context.c
            src/secp256k1/src/group.h
            src/secp256k1/src/group_impl.h
            src/secp256k1/src/hash.h
            src/secp256k1/src/hash_impl.h
            src/secp256k1/src/java/org_bitcoin_NativeSecp256k1.c
            src/secp256k1/src/java/org_bitcoin_NativeSecp256k1.h
            src/secp256k1/src/java/org_bitcoin_Secp256k1Context.c
            src/secp256k1/src/java/org_bitcoin_Secp256k1Context.h
            src/secp256k1/src/libsecp256k1-config.h
            src/secp256k1/src/modules/ecdh/main_impl.h
            src/secp256k1/src/modules/ecdh/tests_impl.h
            src/secp256k1/src/modules/recovery/main_impl.h
            src/secp256k1/src/modules/recovery/tests_impl.h
            src/secp256k1/src/modules/schnorr/main_impl.h
            src/secp256k1/src/modules/schnorr/schnorr.h
            src/secp256k1/src/modules/schnorr/schnorr_impl.h
            src/secp256k1/src/modules/schnorr/test_impl.h
            src/secp256k1/src/num.h
            src/secp256k1/src/num_gmp.h
            src/secp256k1/src/num_gmp_impl.h
            src/secp256k1/src/num_impl.h
            src/secp256k1/src/scalar.h
            src/secp256k1/src/scalar_4x64.h
            src/secp256k1/src/scalar_4x64_impl.h
            src/secp256k1/src/scalar_8x32.h
            src/secp256k1/src/scalar_8x32_impl.h
            src/secp256k1/src/scalar_impl.h
            src/secp256k1/src/scalar_low.h
            src/secp256k1/src/scalar_low_impl.h
            src/secp256k1/src/secp256k1.c
            src/secp256k1/src/testrand.h
            src/secp256k1/src/testrand_impl.h
            src/secp256k1/src/tests.c
            src/secp256k1/src/tests_exhaustive.c
            src/secp256k1/src/util.h
            src/serialize.h
            src/spentindex.h
            src/spork.cpp
            src/spork.h
            src/stake.cpp
            src/stake.h
            src/streams.h
            src/support/allocators/zeroafterfree.h
            src/support/cleanse.cpp
            src/support/cleanse.h
            src/support/events.h
            src/sync.cpp
            src/sync.h
            src/test/accounting_tests.cpp
            src/test/alert_tests.cpp
            src/test/allocator_tests.cpp
            src/test/arith_uint256_tests.cpp
            src/test/base32_tests.cpp
            src/test/base58_tests.cpp
            src/test/base64_tests.cpp
            src/test/bignum.h
            src/test/bip32_tests.cpp
            src/test/bloom_tests.cpp
            src/test/checkblock_tests.cpp
            src/test/Checkpoints_tests.cpp
            src/test/coins_tests.cpp
            src/test/compress_tests.cpp
            src/test/crypto_tests.cpp
            src/test/cuckoocache_tests.cpp
            src/test/DoS_tests.cpp
            src/test/getarg_tests.cpp
            src/test/hash_tests.cpp
            src/test/key_tests.cpp
            src/test/main_tests.cpp
            src/test/mempool_tests.cpp
            src/test/miner_tests.cpp
            src/test/mruset_tests.cpp
            src/test/multisig_tests.cpp
            src/test/netbase_tests.cpp
            src/test/pmt_tests.cpp
            src/test/rpc_tests.cpp
            src/test/rpc_wallet_tests.cpp
            src/test/sanity_tests.cpp
            src/test/scriptnum_tests.cpp
            src/test/script_P2SH_tests.cpp
            src/test/script_tests.cpp
            src/test/serialize_tests.cpp
            src/test/sighash_tests.cpp
            src/test/sigopcount_tests.cpp
            src/test/skiplist_tests.cpp
            src/test/test_lux.cpp
            src/test/timedata_tests.cpp
            src/test/transaction_tests.cpp
            src/test/uint256_tests.cpp
            src/test/univalue_tests.cpp
            src/test/util_tests.cpp
            src/test/wallet_tests.cpp
            src/threadsafety.h
            src/timedata.cpp
            src/timedata.h
            src/tinyformat.h
            src/txdb.cpp
            src/txdb.h
            src/txmempool.cpp
            src/txmempool.h
            src/uint256.cpp
            src/uint256.h
            src/uint512.h
            src/ui_interface.h
            src/undo.h
            src/univalue/gen.cpp
            src/univalue/univalue.cpp
            src/univalue/univalue.h
            src/univalue/univalue_escapes.h
            src/univalue/univalue_read.cpp
            src/univalue/univalue_utffilter.h
            src/univalue/univalue_write.cpp
            src/util.cpp
            src/util.h
            src/utilmoneystr.cpp
            src/utilmoneystr.h
            src/utilstrencodings.cpp
            src/utilstrencodings.h
            src/utiltime.cpp
            src/utiltime.h
            src/validationinterface.cpp
            src/validationinterface.h
            src/version.h
            src/versionbits.cpp
            src/versionbits.h
            src/wallet.cpp
            src/wallet.h
            src/walletdb.cpp
            src/walletdb.h
            src/wallet_ismine.cpp
            src/wallet_ismine.h
            src/zmq/zmqabstractnotifier.cpp
            src/zmq/zmqabstractnotifier.h
            src/zmq/zmqconfig.h
            src/zmq/zmqnotificationinterface.cpp
            src/zmq/zmqnotificationinterface.h
            src/zmq/zmqpublishnotifier.cpp
            src/zmq/zmqpublishnotifier.h
            )

    add_library(noexecutable ${SOURCE_FILES})
endif()
