

#include <QtGlobal>

// Automatically generated by extract_strings.py
#ifdef __GNUC__
#define UNUSED __attribute__((unused))
#else
#define UNUSED
#endif
static const char UNUSED *lux_strings[] = {
QT_TRANSLATE_NOOP("QPlatformTheme", "Cancel"),
QT_TRANSLATE_NOOP("QPlatformTheme", "Close"),
QT_TRANSLATE_NOOP("QPlatformTheme", "Apply"),
QT_TRANSLATE_NOOP("QPlatformTheme", "&Save"),
QT_TRANSLATE_NOOP("QPlatformTheme", "&Yes"),
QT_TRANSLATE_NOOP("QPlatformTheme", "&No"),
QT_TRANSLATE_NOOP("QPlatformTheme", "OK"),
QT_TRANSLATE_NOOP("lux-core", " or address book entries might be missing or incorrect"),
QT_TRANSLATE_NOOP("lux-core", ""
"'importprivkey' finished successfully. Please restart Luxcore wallet with '-"
"rescan' option. Otherwise, transaction data"),
QT_TRANSLATE_NOOP("lux-core", ""
"'importprivkey' with 'Rescan' option finished successfully. Please restart "
"your Luxcore wallet. Otherwise, transaction data"),
QT_TRANSLATE_NOOP("lux-core", ""
"(1 = keep tx meta data e.g. account owner and payment request information, 2 "
"= drop tx meta data)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Allow JSON-RPC connections from specified source. Valid for <ip> are a "
"single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or "
"a network/CIDR (e.g. 1.2.3.4/24). This option can be specified multiple times"),
QT_TRANSLATE_NOOP("lux-core", ""
"Bind to given address and always listen on it. Use [host]:port notation for "
"IPv6"),
QT_TRANSLATE_NOOP("lux-core", ""
"Bind to given address and whitelist peers connecting to it. Use [host]:port "
"notation for IPv6"),
QT_TRANSLATE_NOOP("lux-core", ""
"Bind to given address to listen for JSON-RPC connections. Use [host]:port "
"notation for IPv6. This option can be specified multiple times (default: "
"bind to all interfaces)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Cannot obtain a lock on data directory %s. %s is probably already running."),
QT_TRANSLATE_NOOP("lux-core", ""
"Cannot obtain a lock on data directory %s. Luxcore is probably already "
"running."),
QT_TRANSLATE_NOOP("lux-core", ""
"Change automatic finalized budget voting behavior. mode=auto: Vote for only "
"exact finalized budget match to my generated budget. (string, default: auto)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Continuously rate-limit free transactions to <n>*1000 bytes per minute "
"(default:%u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Create new files with system default permissions, instead of umask 077 (only "
"effective with disabled wallet functionality)"),
QT_TRANSLATE_NOOP("lux-core", ""
"DarkSend uses exact denominated amounts to send funds, you might simply need "
"to anonymize some more coins."),
QT_TRANSLATE_NOOP("lux-core", ""
"Delete all wallet transactions and only recover those parts of the "
"blockchain through -rescan on startup"),
QT_TRANSLATE_NOOP("lux-core", ""
"Distributed under the MIT software license, see the accompanying file "
"COPYING or <http://www.opensource.org/licenses/mit-license.php>."),
QT_TRANSLATE_NOOP("lux-core", ""
"Enable instantx, show confirmations for locked transactions (bool, default: "
"%s)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Enable use of automated darksend for funds stored in this wallet (0-1, "
"default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Enter regression test mode, which uses a special chain in which blocks can "
"be solved instantly."),
QT_TRANSLATE_NOOP("lux-core", ""
"Error loading %s: You need to upgrade the wallet to enable HD on a non-HD "
"wallet"),
QT_TRANSLATE_NOOP("lux-core", ""
"Error: Listening for incoming connections failed (listen returned error %s)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Error: Unsupported argument -socks found. Setting SOCKS version isn't "
"possible anymore, only SOCKS5 proxies are supported."),
QT_TRANSLATE_NOOP("lux-core", ""
"Execute command when a relevant alert is received or we see a really long "
"fork (%s in cmd is replaced by message)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Execute command when a wallet transaction changes (%s in cmd is replaced by "
"TxID)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Execute command when the best block changes (%s in cmd is replaced by block "
"hash)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Fees (in LUX/Kb) smaller than this are considered zero fee for relaying "
"(default: %s)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Fees (in LUX/Kb) smaller than this are considered zero fee for transaction "
"creation (default: %s)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Flush database activity from memory pool to disk log every <n> megabytes "
"(default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Found unconfirmed denominated outputs, will wait till they confirm to "
"continue."),
QT_TRANSLATE_NOOP("lux-core", ""
"How thorough the block verification of -checkblocks is (0-4, default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"If paytxfee is not set, include enough fee so transactions begin "
"confirmation on average within n blocks (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"In this mode -genproclimit controls how many blocks are generated "
"immediately."),
QT_TRANSLATE_NOOP("lux-core", ""
"InstantX requires inputs with at least 6 confirmations, you might need to "
"wait a few minutes and try again."),
QT_TRANSLATE_NOOP("lux-core", ""
"Invalid amount for -maxtxfee=<amount>: '%s' (must be at least the minrelay "
"fee of %s to prevent stuck transactions)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Log transaction priority and fee per kB when mining blocks (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Maintain a full EVM log index, used by searchlogs and gettransactionreceipt "
"rpc calls (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Maintain a full address index, used to query for the balance, txids and "
"unspent outputs for addresses (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Maintain a full spent index, used to query the spending txid and input index "
"for an outpoint (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Maintain a full transaction index, used by the getrawtransaction rpc call "
"(default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Make sure to encrypt your wallet and delete all non-encrypted backups after "
"you verified that wallet works!"),
QT_TRANSLATE_NOOP("lux-core", ""
"Maximum size of data in data carrier transactions we relay and mine "
"(default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Maximum total fees to use in a single wallet transaction, setting too low "
"may abort large transactions (default: %s)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Number of seconds to keep misbehaving peers from reconnecting (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Output debugging information (default: %u, supplying <category> is optional)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Provide liquidity to Darksend by infrequently mixing coins on a continual "
"basis (0-100, default: %u, 1=very frequent, high fees, 100=very infrequent, "
"low fees)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Prune configured below the minimum of %d MB.  Please use a higher number."),
QT_TRANSLATE_NOOP("lux-core", ""
"Prune: last wallet synchronisation goes beyond pruned data. You need to -"
"reindex (download the whole blockchain again in case of pruned node)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Query for peer addresses via DNS lookup, if low on addresses (default: 1 "
"unless -connect)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Reduce storage requirements by pruning (deleting) old blocks. This mode "
"disables wallet support and is incompatible with -txindex."),
QT_TRANSLATE_NOOP("lux-core", ""
"Require high priority for relaying free or low-fee transactions (default:%u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Rescan aborted by user. Please restart your Luxcore wallet with '-rescan' "
"option. Otherwise, transaction data"),
QT_TRANSLATE_NOOP("lux-core", ""
"Send trace/debug info to console instead of debug.log file (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Set maximum size of high-priority/low-fee transactions in bytes (default: %d)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Set the number of script verification threads (1 to %d, 0 = auto, <0 = leave "
"that many cores free, default: %d)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Set the number of threads for coin generation if enabled (-1 = all cores, "
"default: %d)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Show N confirmations for a successfully locked transaction (0-9999, default: "
"%u)"),
QT_TRANSLATE_NOOP("lux-core", ""
"The block database contains a block which appears to be from the future. "
"This may be due to your computer's date and time being set incorrectly. Only "
"rebuild the block database if you are sure that your computer's date and "
"time are correct"),
QT_TRANSLATE_NOOP("lux-core", ""
"This is a pre-release test build - use at your own risk - do not use for "
"mining or merchant applications"),
QT_TRANSLATE_NOOP("lux-core", ""
"This product includes software developed by the OpenSSL Project for use in "
"the OpenSSL Toolkit <https://www.openssl.org/> and cryptographic software "
"written by Eric Young and UPnP software written by Thomas Bernard."),
QT_TRANSLATE_NOOP("lux-core", ""
"Unable to bind to %s on this computer. Luxcore is probably already running."),
QT_TRANSLATE_NOOP("lux-core", ""
"Unable to locate enough DarkSend denominated funds for this transaction."),
QT_TRANSLATE_NOOP("lux-core", ""
"Unable to locate enough DarkSend non-denominated funds for this transaction "
"that are not equal 10000 LUX."),
QT_TRANSLATE_NOOP("lux-core", ""
"Unable to locate enough funds for this transaction that are not equal 10000 "
"LUX."),
QT_TRANSLATE_NOOP("lux-core", ""
"Use hierarchical deterministic key generation (HD) after bip32. Only has "
"effect during wallet creation/first start"),
QT_TRANSLATE_NOOP("lux-core", ""
"Use separate SOCKS5 proxy to reach peers via Tor hidden services (default: "
"%s)"),
QT_TRANSLATE_NOOP("lux-core", ""
"User defined memonic passphrase for HD wallet (bip39). Only has effect "
"during wallet creation/first start (default: randomly generated)"),
QT_TRANSLATE_NOOP("lux-core", ""
"User defined mnemonic for HD wallet (bip39). Only has effect during wallet "
"creation/first start (default: randomly generated)"),
QT_TRANSLATE_NOOP("lux-core", ""
"User defined seed for HD wallet (should be in hex). Only has effect during "
"wallet creation/first start (default: randomly generated)"),
QT_TRANSLATE_NOOP("lux-core", ""
"Warning: -maxtxfee is set very high! Fees this large could be paid on a "
"single transaction."),
QT_TRANSLATE_NOOP("lux-core", ""
"Warning: -paytxfee is set very high! This is the transaction fee you will "
"pay if you send a transaction."),
QT_TRANSLATE_NOOP("lux-core", ""
"Warning: Please check that your computer's date and time are correct! If "
"your clock is wrong Luxcore will not work properly."),
QT_TRANSLATE_NOOP("lux-core", ""
"Warning: Reverting this setting requires re-downloading the entire "
"blockchain."),
QT_TRANSLATE_NOOP("lux-core", ""
"Warning: The network does not appear to fully agree! Some miners appear to "
"be experiencing issues."),
QT_TRANSLATE_NOOP("lux-core", ""
"Warning: We do not appear to fully agree with our peers! You may need to "
"upgrade, or other nodes may need to upgrade."),
QT_TRANSLATE_NOOP("lux-core", ""
"Warning: error reading wallet.dat! All keys read correctly, but transaction "
"data or address book entries might be missing or incorrect."),
QT_TRANSLATE_NOOP("lux-core", ""
"Warning: wallet.dat corrupt, data salvaged! Original wallet.dat saved as "
"wallet.{timestamp}.bak in %s; if your balance or transactions are incorrect "
"you should restore from a backup."),
QT_TRANSLATE_NOOP("lux-core", ""
"Whitelist peers connecting from the given netmask or IP address. Can be "
"specified multiple times."),
QT_TRANSLATE_NOOP("lux-core", ""
"Whitelisted peers cannot be DoS banned and their transactions are always "
"relayed, even if they are already in the mempool, useful e.g. for a gateway"),
QT_TRANSLATE_NOOP("lux-core", ""
"You must specify a masternodeprivkey in the configuration. Please see "
"documentation for help."),
QT_TRANSLATE_NOOP("lux-core", ""
"You need to rebuild the database using -reindex to go back to unpruned "
"mode.  This will redownload the entire blockchain"),
QT_TRANSLATE_NOOP("lux-core", ""
"You need to rebuild the database using -reindex-chainstate to enable -"
"logevents"),
QT_TRANSLATE_NOOP("lux-core", "(default: %s)"),
QT_TRANSLATE_NOOP("lux-core", "(default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "(default: 0 = disable pruning blocks,"),
QT_TRANSLATE_NOOP("lux-core", "(default: 1)"),
QT_TRANSLATE_NOOP("lux-core", "<category> can be:"),
QT_TRANSLATE_NOOP("lux-core", ">%u = target size in MiB to use for block files)"),
QT_TRANSLATE_NOOP("lux-core", "Accept command line and JSON-RPC commands"),
QT_TRANSLATE_NOOP("lux-core", "Accept connections from outside (default: 1 if no -proxy or -connect)"),
QT_TRANSLATE_NOOP("lux-core", "Accept public REST requests (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Acceptable ciphers (default: %s)"),
QT_TRANSLATE_NOOP("lux-core", "Add a node to connect to and attempt to keep the connection open"),
QT_TRANSLATE_NOOP("lux-core", "Allow DNS lookups for -addnode, -seednode and -connect"),
QT_TRANSLATE_NOOP("lux-core", "Already have that input."),
QT_TRANSLATE_NOOP("lux-core", "Always query for peer addresses via DNS lookup (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Attempt to recover private keys from a corrupt wallet.dat"),
QT_TRANSLATE_NOOP("lux-core", "Block creation options:"),
QT_TRANSLATE_NOOP("lux-core", "Can't denominate: no compatible inputs left."),
QT_TRANSLATE_NOOP("lux-core", "Cannot downgrade wallet"),
QT_TRANSLATE_NOOP("lux-core", "Cannot resolve -bind address: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Cannot resolve -externalip address: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Cannot resolve -whitebind address: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Cannot write default address"),
QT_TRANSLATE_NOOP("lux-core", "Change index out of range"),
QT_TRANSLATE_NOOP("lux-core", "Collateral is not valid."),
QT_TRANSLATE_NOOP("lux-core", "Collateral not valid."),
QT_TRANSLATE_NOOP("lux-core", "Connect only to the specified node(s)"),
QT_TRANSLATE_NOOP("lux-core", "Connect through SOCKS5 proxy"),
QT_TRANSLATE_NOOP("lux-core", "Connect to a node to retrieve peer addresses, and disconnect"),
QT_TRANSLATE_NOOP("lux-core", "Connection options:"),
QT_TRANSLATE_NOOP("lux-core", "Copyright (C) 2009-%i The Bitcoin Core Developers"),
QT_TRANSLATE_NOOP("lux-core", "Copyright (C) 2014-%i The Dash Core Developers"),
QT_TRANSLATE_NOOP("lux-core", "Copyright (C) 2017-%i The LUX-Core Developers"),
QT_TRANSLATE_NOOP("lux-core", "Corrupted block database detected"),
QT_TRANSLATE_NOOP("lux-core", "Darksend is disabled."),
QT_TRANSLATE_NOOP("lux-core", "Darksend options:"),
QT_TRANSLATE_NOOP("lux-core", "Debugging/Testing options:"),
QT_TRANSLATE_NOOP("lux-core", "Disable safemode, override a real safe mode event (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Discover own IP address (default: 1 when listening and no -externalip)"),
QT_TRANSLATE_NOOP("lux-core", "Do not load the wallet and disable wallet RPC calls"),
QT_TRANSLATE_NOOP("lux-core", "Do you want to rebuild the block database now?"),
QT_TRANSLATE_NOOP("lux-core", "Done loading"),
QT_TRANSLATE_NOOP("lux-core", "Enable publish hash block in <address>"),
QT_TRANSLATE_NOOP("lux-core", "Enable publish hash transaction (locked via InstanTX) in <address>"),
QT_TRANSLATE_NOOP("lux-core", "Enable publish hash transaction in <address>"),
QT_TRANSLATE_NOOP("lux-core", "Enable publish raw block in <address>"),
QT_TRANSLATE_NOOP("lux-core", "Enable publish raw transaction (locked via InstanTX) in <address>"),
QT_TRANSLATE_NOOP("lux-core", "Enable publish raw transaction in <address>"),
QT_TRANSLATE_NOOP("lux-core", "Enable the client to act as a masternode (0-1, default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Entries are full."),
QT_TRANSLATE_NOOP("lux-core", "Error connecting to masternode."),
QT_TRANSLATE_NOOP("lux-core", "Error initializing block database"),
QT_TRANSLATE_NOOP("lux-core", "Error initializing wallet database environment %s!"),
QT_TRANSLATE_NOOP("lux-core", "Error loading %s: You can't disable HD on a already existing HD wallet"),
QT_TRANSLATE_NOOP("lux-core", "Error loading block database"),
QT_TRANSLATE_NOOP("lux-core", "Error loading wallet.dat"),
QT_TRANSLATE_NOOP("lux-core", "Error loading wallet.dat: Wallet corrupted"),
QT_TRANSLATE_NOOP("lux-core", "Error loading wallet.dat: Wallet requires newer version of Luxcore"),
QT_TRANSLATE_NOOP("lux-core", "Error opening block database"),
QT_TRANSLATE_NOOP("lux-core", "Error reading from database, shutting down."),
QT_TRANSLATE_NOOP("lux-core", "Error recovering public key."),
QT_TRANSLATE_NOOP("lux-core", "Error"),
QT_TRANSLATE_NOOP("lux-core", "Error: A fatal internal error occured, see debug.log for details"),
QT_TRANSLATE_NOOP("lux-core", "Error: A fatal internal error occurred, see debug.log for details"),
QT_TRANSLATE_NOOP("lux-core", "Error: Disk space is low!"),
QT_TRANSLATE_NOOP("lux-core", "Error: Unsupported argument -tor found, use -onion."),
QT_TRANSLATE_NOOP("lux-core", "Error: Wallet locked, unable to create transaction!"),
QT_TRANSLATE_NOOP("lux-core", "Error: You already have pending entries in the Darksend pool"),
QT_TRANSLATE_NOOP("lux-core", "Error: can't select current denominated inputs"),
QT_TRANSLATE_NOOP("lux-core", "Failed to listen on any port. Use -listen=0 if you want this."),
QT_TRANSLATE_NOOP("lux-core", "Fee (in LUX/kB) to add to transactions you send (default: %s)"),
QT_TRANSLATE_NOOP("lux-core", "Force safe mode (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Generate coins (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "How many blocks to check at startup (default: %u, 0 = all)"),
QT_TRANSLATE_NOOP("lux-core", "If <category> is not supplied, output all debugging information."),
QT_TRANSLATE_NOOP("lux-core", "Importing..."),
QT_TRANSLATE_NOOP("lux-core", "Imports blocks from external blk000??.dat file"),
QT_TRANSLATE_NOOP("lux-core", "Include IP addresses in debug output (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Incompatible mode."),
QT_TRANSLATE_NOOP("lux-core", "Incompatible version."),
QT_TRANSLATE_NOOP("lux-core", "Incorrect or no genesis block found. Wrong datadir for network?"),
QT_TRANSLATE_NOOP("lux-core", "Information"),
QT_TRANSLATE_NOOP("lux-core", "Initialization sanity check failed. Luxcore is shutting down."),
QT_TRANSLATE_NOOP("lux-core", "Input is not valid."),
QT_TRANSLATE_NOOP("lux-core", "InstanTX options:"),
QT_TRANSLATE_NOOP("lux-core", "Insufficient funds."),
QT_TRANSLATE_NOOP("lux-core", "Invalid -onion address: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Invalid -proxy address: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Invalid amount for -maxtxfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Invalid amount for -minrelaytxfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Invalid amount for -mintxfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Invalid amount for -paytxfee=<amount>: '%s' (must be at least %s)"),
QT_TRANSLATE_NOOP("lux-core", "Invalid amount for -paytxfee=<amount>: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Invalid amount for -reservebalance=<amount>"),
QT_TRANSLATE_NOOP("lux-core", "Invalid masternodeprivkey. Please see documenation."),
QT_TRANSLATE_NOOP("lux-core", "Invalid netmask specified in -whitelist: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Invalid private key."),
QT_TRANSLATE_NOOP("lux-core", "Invalid script detected."),
QT_TRANSLATE_NOOP("lux-core", "Keep N LUX anonymized (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Keep at most <n> unconnectable transactions in memory (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Keypool ran out, please call keypoolrefill first"),
QT_TRANSLATE_NOOP("lux-core", "Last Darksend was too recent."),
QT_TRANSLATE_NOOP("lux-core", "Last successful darksend action was too recent."),
QT_TRANSLATE_NOOP("lux-core", "Limit size of signature cache to <n> entries (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Listen for JSON-RPC connections on <port> (default: %u or testnet: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Listen for connections on <port> (default: %u or testnet: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Loading addresses..."),
QT_TRANSLATE_NOOP("lux-core", "Loading block index..."),
QT_TRANSLATE_NOOP("lux-core", "Loading wallet... (%3.2f %%)"),
QT_TRANSLATE_NOOP("lux-core", "Loading wallet..."),
QT_TRANSLATE_NOOP("lux-core", "Lock masternodes from masternode configuration file (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Logs all EVM LOG opcode operations to the file vmExecLogs.json"),
QT_TRANSLATE_NOOP("lux-core", "Maintain at most <n> connections to peers (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Make the wallet broadcast transactions"),
QT_TRANSLATE_NOOP("lux-core", "Masternode options:"),
QT_TRANSLATE_NOOP("lux-core", "Masternode queue is full."),
QT_TRANSLATE_NOOP("lux-core", "Masternode:"),
QT_TRANSLATE_NOOP("lux-core", "Maximum per-connection receive buffer, <n>*1000 bytes (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Maximum per-connection send buffer, <n>*1000 bytes (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Missing input transaction information."),
QT_TRANSLATE_NOOP("lux-core", "Mnemonic passphrase is too long, must be at most 256 characters"),
QT_TRANSLATE_NOOP("lux-core", "Need to specify a port with -whitebind: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "No compatible masternode found."),
QT_TRANSLATE_NOOP("lux-core", "No funds detected in need of denominating."),
QT_TRANSLATE_NOOP("lux-core", "No masternodes detected."),
QT_TRANSLATE_NOOP("lux-core", "No matching denominations found for mixing."),
QT_TRANSLATE_NOOP("lux-core", "Node relay options:"),
QT_TRANSLATE_NOOP("lux-core", "Non-standard public key detected."),
QT_TRANSLATE_NOOP("lux-core", "Not compatible with existing transactions."),
QT_TRANSLATE_NOOP("lux-core", "Not enough file descriptors available."),
QT_TRANSLATE_NOOP("lux-core", "Not in the masternode list."),
QT_TRANSLATE_NOOP("lux-core", "Number of automatic wallet backups (default: 10)"),
QT_TRANSLATE_NOOP("lux-core", "Only accept block chain matching built-in checkpoints (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Only connect to nodes in network <net> (ipv4, ipv6 or onion)"),
QT_TRANSLATE_NOOP("lux-core", "Options:"),
QT_TRANSLATE_NOOP("lux-core", "Password for JSON-RPC connections"),
QT_TRANSLATE_NOOP("lux-core", "Prepend debug output with timestamp (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Prune cannot be configured with a negative value."),
QT_TRANSLATE_NOOP("lux-core", "Prune mode is incompatible with -txindex."),
QT_TRANSLATE_NOOP("lux-core", "Pruning blockstore..."),
QT_TRANSLATE_NOOP("lux-core", "RPC SSL options: (see the Bitcoin Wiki for SSL setup instructions)"),
QT_TRANSLATE_NOOP("lux-core", "RPC server options:"),
QT_TRANSLATE_NOOP("lux-core", "RPC support for HTTP persistent connections (default: %d)"),
QT_TRANSLATE_NOOP("lux-core", "Randomly drop 1 of every <n> network messages"),
QT_TRANSLATE_NOOP("lux-core", "Randomly fuzz 1 of every <n> network messages"),
QT_TRANSLATE_NOOP("lux-core", "Rebuild block chain index from current blk000??.dat files"),
QT_TRANSLATE_NOOP("lux-core", "Rebuild chain state from the currently indexed blocks"),
QT_TRANSLATE_NOOP("lux-core", "Receive and display P2P network alerts (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Relay and mine data carrier transactions (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Relay non-P2SH multisig (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Rescan the block chain for missing wallet transactions"),
QT_TRANSLATE_NOOP("lux-core", "Rescanning..."),
QT_TRANSLATE_NOOP("lux-core", "Run a thread to flush wallet periodically (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Run in the background as a daemon and accept commands"),
QT_TRANSLATE_NOOP("lux-core", "Send transactions as zero-fee transactions if possible (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Server certificate file (default: %s)"),
QT_TRANSLATE_NOOP("lux-core", "Server private key (default: %s)"),
QT_TRANSLATE_NOOP("lux-core", "Session not complete!"),
QT_TRANSLATE_NOOP("lux-core", "Session timed out (30 seconds), please resubmit."),
QT_TRANSLATE_NOOP("lux-core", "Set database cache size in megabytes (%d to %d, default: %d)"),
QT_TRANSLATE_NOOP("lux-core", "Set external address:port to get to this masternode (example: %s)"),
QT_TRANSLATE_NOOP("lux-core", "Set key pool size to <n> (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Set maximum block size in bytes (default: %d)"),
QT_TRANSLATE_NOOP("lux-core", "Set minimum block size in bytes (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Set number of debug log files"),
QT_TRANSLATE_NOOP("lux-core", "Set the masternode private key"),
QT_TRANSLATE_NOOP("lux-core", "Set the number of threads to service RPC calls (default: %d)"),
QT_TRANSLATE_NOOP("lux-core", "Sets the DB_PRIVATE flag in the wallet db environment (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Show all debugging options (usage: --help -help-debug)"),
QT_TRANSLATE_NOOP("lux-core", "Shrink debug.log file on client startup (default: 1 when no -debug)"),
QT_TRANSLATE_NOOP("lux-core", "Signing failed."),
QT_TRANSLATE_NOOP("lux-core", "Signing timed out, please resubmit."),
QT_TRANSLATE_NOOP("lux-core", "Signing transaction failed"),
QT_TRANSLATE_NOOP("lux-core", "Specify configuration file (default: %s)"),
QT_TRANSLATE_NOOP("lux-core", "Specify connection timeout in milliseconds (minimum: 1, default: %d)"),
QT_TRANSLATE_NOOP("lux-core", "Specify data directory"),
QT_TRANSLATE_NOOP("lux-core", "Specify masternode configuration file (default: %s)"),
QT_TRANSLATE_NOOP("lux-core", "Specify pid file (default: %s)"),
QT_TRANSLATE_NOOP("lux-core", "Specify wallet file (within data directory)"),
QT_TRANSLATE_NOOP("lux-core", "Specify your own public address"),
QT_TRANSLATE_NOOP("lux-core", "Spend unconfirmed change when sending transactions (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Stake your coins to support network and gain reward (default: %s)"),
QT_TRANSLATE_NOOP("lux-core", "Stop running after importing blocks from disk (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "This help message"),
QT_TRANSLATE_NOOP("lux-core", "This is experimental software."),
QT_TRANSLATE_NOOP("lux-core", "This is intended for regression testing tools and app development."),
QT_TRANSLATE_NOOP("lux-core", "This is not a masternode."),
QT_TRANSLATE_NOOP("lux-core", "Threshold for disconnecting misbehaving peers (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Transaction amount too small"),
QT_TRANSLATE_NOOP("lux-core", "Transaction amounts must be positive"),
QT_TRANSLATE_NOOP("lux-core", "Transaction created successfully."),
QT_TRANSLATE_NOOP("lux-core", "Transaction fees are too high."),
QT_TRANSLATE_NOOP("lux-core", "Transaction not valid."),
QT_TRANSLATE_NOOP("lux-core", "Unable to bind to %s on this computer (bind returned error %s)"),
QT_TRANSLATE_NOOP("lux-core", "Unable to generate keys"),
QT_TRANSLATE_NOOP("lux-core", "Unable to sign masternode payment winner, wrong key?"),
QT_TRANSLATE_NOOP("lux-core", "Unable to sign spork message, wrong key?"),
QT_TRANSLATE_NOOP("lux-core", "Unable to start HTTP server. See debug log for details."),
QT_TRANSLATE_NOOP("lux-core", "Unknown address type '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Unknown change type '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Unknown network specified in -onlynet: '%s'"),
QT_TRANSLATE_NOOP("lux-core", "Upgrade wallet to latest format"),
QT_TRANSLATE_NOOP("lux-core", "Use N separate masternodes to anonymize funds  (2-8, default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Use OpenSSL (https) for JSON-RPC connections"),
QT_TRANSLATE_NOOP("lux-core", "Use UPnP to map the listening port (default: %u)"),
QT_TRANSLATE_NOOP("lux-core", "Use UPnP to map the listening port (default: 1 when listening)"),
QT_TRANSLATE_NOOP("lux-core", "Use the SegWit test network"),
QT_TRANSLATE_NOOP("lux-core", "Use the test network"),
QT_TRANSLATE_NOOP("lux-core", "Username for JSON-RPC connections"),
QT_TRANSLATE_NOOP("lux-core", "Value more than Darksend pool maximum allows."),
QT_TRANSLATE_NOOP("lux-core", "Verifying blocks..."),
QT_TRANSLATE_NOOP("lux-core", "Verifying wallet..."),
QT_TRANSLATE_NOOP("lux-core", "Wallet %s resides outside data directory %s"),
QT_TRANSLATE_NOOP("lux-core", "Wallet is locked."),
QT_TRANSLATE_NOOP("lux-core", "Wallet needed to be rewritten: restart Luxcore to complete"),
QT_TRANSLATE_NOOP("lux-core", "Wallet options:"),
QT_TRANSLATE_NOOP("lux-core", "Wallet window title"),
QT_TRANSLATE_NOOP("lux-core", "Warning"),
QT_TRANSLATE_NOOP("lux-core", "Warning: This version is obsolete, upgrade required!"),
QT_TRANSLATE_NOOP("lux-core", "Warning: Unsupported argument -benchmark ignored, use -debug=bench."),
QT_TRANSLATE_NOOP("lux-core", "Warning: Unsupported argument -debugnet ignored, use -debug=net."),
QT_TRANSLATE_NOOP("lux-core", "Warning: unknown new rules activated (versionbit %i)"),
QT_TRANSLATE_NOOP("lux-core", "Wrong state."),
QT_TRANSLATE_NOOP("lux-core", "You need to rebuild the database using -reindex to change -txindex"),
QT_TRANSLATE_NOOP("lux-core", "Zapping all transactions from wallet..."),
QT_TRANSLATE_NOOP("lux-core", "ZeroMQ notification options:"),
QT_TRANSLATE_NOOP("lux-core", "on startup"),
QT_TRANSLATE_NOOP("lux-core", "wallet.dat corrupt, salvage failed"),
};
